INSERT INTO `products` VALUES(6797,28,"djakwe (madjakwe)","singe","_","active");
INSERT INTO `products` VALUES(6798,28,"dremela","chauve-souris","_","active");
INSERT INTO `products` VALUES(6799,28,"dzianyindri","caméléon","_","active");
INSERT INTO `products` VALUES(6800,28,"funga","civette, rasse","_","active");
INSERT INTO `products` VALUES(6801,28,"kamatrindri","gecko","_","active");
INSERT INTO `products` VALUES(6802,28,"komba","maki","_","active");
INSERT INTO `products` VALUES(6803,28,"kowa (makowa)","escargot","_","active");
INSERT INTO `products` VALUES(6804,28,"landra","tangue / hérisson","_","active");
INSERT INTO `products` VALUES(6805,28,"mbwa nyeha","chacal","_","active");
INSERT INTO `products` VALUES(6806,28,"ndovu","éléphant","_","active");
INSERT INTO `products` VALUES(6807,28,"ndrema","roussette","_","active");
INSERT INTO `products` VALUES(6808,28,"ngamia","chameau","_","active");
INSERT INTO `products` VALUES(6809,28,"ngizi / ngwizi","lézard","_","active");
INSERT INTO `products` VALUES(6810,28,"nyoha","serpent","_","active");
INSERT INTO `products` VALUES(6811,28,"puhu (mavuhu)","rat","_","active");
INSERT INTO `products` VALUES(6812,28,"puruku nyeha","phacochère","_","active");
INSERT INTO `products` VALUES(6813,28,"shikwetse (zi-)","souris","_","active");
INSERT INTO `products` VALUES(6814,28,"shinyama (zinyama)","animal","_","active");
INSERT INTO `products` VALUES(6815,28,"shiwatrotro (zi-)","grenouille","_","active");
INSERT INTO `products` VALUES(6816,28,"simba","lion","_","active");
INSERT INTO `products` VALUES(6817,28,"sungura","lièvre","_","active");
INSERT INTO `products` VALUES(6818,28,"trutri (marutri)","souris / mulot","_","active");
INSERT INTO `products` VALUES(6819,28,"vwai","crocodile","_","active");
INSERT INTO `products` VALUES(6820,28,"baribari (mabaribari)","mouton","_","active");
INSERT INTO `products` VALUES(6821,28,"bewe (mabewe)","bouc","_","active");
INSERT INTO `products` VALUES(6822,28,"farasi","cheval","_","active");
INSERT INTO `products` VALUES(6823,28,"kondzo (mahondzo)","taureau","_","active");
INSERT INTO `products` VALUES(6824,28,"lape","lapin","_","active");
INSERT INTO `products` VALUES(6825,28,"mbuzi","chèvre","_","active");
INSERT INTO `products` VALUES(6826,28,"mbwa","chien","_","active");
INSERT INTO `products` VALUES(6827,28,"mpaha / paha","chat","_","active");
INSERT INTO `products` VALUES(6828,28,"nyombe","vache / zébu","_","active");
INSERT INTO `products` VALUES(6829,28,"pundra","âne","_","active");
INSERT INTO `products` VALUES(6830,28,"puruku (mavuruku)","cochon / porc","_","active");
INSERT INTO `products` VALUES(6831,28,"bundri / bwindri (ma-)","hibou / chouette","_","active");
INSERT INTO `products` VALUES(6832,28,"banta","canard","_","active");
INSERT INTO `products` VALUES(6833,28,"gawa","corbeau","_","active");
INSERT INTO `products` VALUES(6834,28,"gisi (magisi)","oie","_","active");
INSERT INTO `products` VALUES(6835,28,"kanga","pintade","_","active");
INSERT INTO `products` VALUES(6836,28,"kararauki","perruche","_","active");
INSERT INTO `products` VALUES(6837,28,"kasuku","perroquet","_","active");
INSERT INTO `products` VALUES(6838,28,"kuhu / nkuhu","poule / poulet","_","active");
INSERT INTO `products` VALUES(6839,28,"kukuyi (makukuyi)","coq","_","active");
INSERT INTO `products` VALUES(6840,28,"kulukulu","dindon / dinde","_","active");
INSERT INTO `products` VALUES(6841,28,"kwai (mahwai)","corbeau / corneille","_","active");
INSERT INTO `products` VALUES(6842,28,"kwezi (mahwezi)","aigle / épervier","_","active");
INSERT INTO `products` VALUES(6843,28,"ndiwa","pigeon","_","active");
INSERT INTO `products` VALUES(6844,28,"nyunyi","oiseau","_","active");
INSERT INTO `products` VALUES(6845,28,"shikuru (zikuru)","tourterelle","_","active");
INSERT INTO `products` VALUES(6846,28,"tausi","paon","_","active");
INSERT INTO `products` VALUES(6847,28,"bibi (mabibi)","insecte","_","active");
INSERT INTO `products` VALUES(6848,28,"bibimangidi","chenille","_","active");
INSERT INTO `products` VALUES(6849,28,"dundri (manundri)","moustique","_","active");
INSERT INTO `products` VALUES(6850,28,"furudji (mafurudji)","sauterelle","_","active");
INSERT INTO `products` VALUES(6851,28,"hala","scorpion","_","active");
INSERT INTO `products` VALUES(6852,28,"kalalawi (mahalalawi)","cafard","_","active");
INSERT INTO `products` VALUES(6853,28,"kunguni","puce","_","active");
INSERT INTO `products` VALUES(6854,28,"ndra","pou","_","active");
INSERT INTO `products` VALUES(6855,28,"ndzi","mouche","_","active");
INSERT INTO `products` VALUES(6856,28,"nyoshi","abeille","_","active");
INSERT INTO `products` VALUES(6857,28,"pandzi (mavandzi)","criquet","_","active");
INSERT INTO `products` VALUES(6858,28,"pelapelaka","papillon","_","active");
INSERT INTO `products` VALUES(6859,28,"pepetumani","luciole","_","active");
INSERT INTO `products` VALUES(6860,28,"shitrandrabwibwi","araignée","_","active");
INSERT INTO `products` VALUES(6861,28,"trambwi (marambwi)","scolopendre / millepatte","_","active");
INSERT INTO `products` VALUES(6862,28,"tsutsuhu","fourmi","_","active");
INSERT INTO `products` VALUES(6863,28,"umba","puce de sommier","_","active");
INSERT INTO `products` VALUES(6864,28,"vungo-vungo (ma-)","guêpe","_","active");
INSERT INTO `products` VALUES(6865,28,"mwema / ndjema","inoffensif","_","active");
INSERT INTO `products` VALUES(6866,28,"mbi / kali","féroce","_","active");
INSERT INTO `products` VALUES(6867,28,"nyeha","sauvage","_","active");
INSERT INTO `products` VALUES(6868,28,"ha hatwari","dangereux","_","active");
INSERT INTO `products` VALUES(6869,28,"uwaha kara","faire son nid","_","active");
INSERT INTO `products` VALUES(6870,28,"udya, ula","manger","_","active");
INSERT INTO `products` VALUES(6871,28,"udzaa jwayi","pondre un oeuf","_","active");
INSERT INTO `products` VALUES(6872,28,"udzonya","piquer (insecte)","_","active");
INSERT INTO `products` VALUES(6873,28,"udzumbua","picorer","_","active");
INSERT INTO `products` VALUES(6874,28,"ueuha","voler","_","active");
INSERT INTO `products` VALUES(6875,28,"ufuma","tisser (toile)","_","active");
INSERT INTO `products` VALUES(6876,28,"uhomba","lécher","_","active");
INSERT INTO `products` VALUES(6877,28,"ulia","crier / aboyer / miauler","_","active");
INSERT INTO `products` VALUES(6878,28,"uramba","ramper","_","active");
INSERT INTO `products` VALUES(6879,28,"urema mahofu","griffer","_","active");
INSERT INTO `products` VALUES(6880,28,"urema manyo","mordre","_","active");
INSERT INTO `products` VALUES(6881,28,"urema unyondzi","siffler (serpent / oiseau)","_","active");
INSERT INTO `products` VALUES(6882,28,"uvura gono","ronronner / gronder","_","active");
INSERT INTO `products` VALUES(6883,29,"mbambu, (mi-)","bambou","_","active");
INSERT INTO `products` VALUES(6884,29,"mbuyu, (mi-)","baobab","_","active");
INSERT INTO `products` VALUES(6885,29,"mdaryasini, (mi-)","cannelier","_","active");
INSERT INTO `products` VALUES(6886,29,"mfanasi, (mi-)","jaquier","_","active");
INSERT INTO `products` VALUES(6887,29,"mkafe, (mi-)","caféier","_","active");
INSERT INTO `products` VALUES(6888,29,"mkungumanga, (mi-)","muscadier","_","active");
INSERT INTO `products` VALUES(6889,29,"mlangilangi, (mi-)","ylang-ylang","_","active");
INSERT INTO `products` VALUES(6890,29,"mlanzi, (mi-)","mandarinier","_","active");
INSERT INTO `products` VALUES(6891,29,"mlitshi, (mi-)","letchi","_","active");
INSERT INTO `products` VALUES(6892,29,"msakwa, (mi-)","jujubier","_","active");
INSERT INTO `products` VALUES(6893,29,"mtrendre, (mi-)","dattier","_","active");
INSERT INTO `products` VALUES(6894,29,"muframpe, (mi-)","arbre à pain","_","active");
INSERT INTO `products` VALUES(6895,29,"muhaju, (mi-)","tamarinier","_","active");
INSERT INTO `products` VALUES(6896,29,"muhôko, (mi-)","palétuvier","_","active");
INSERT INTO `products` VALUES(6897,29,"mukarafu, (mi-)","giroflier","_","active");
INSERT INTO `products` VALUES(6898,29,"mukonokono, (mi-)","corossolier","_","active");
INSERT INTO `products` VALUES(6899,29,"mulimu, (mi-)","citronnier","_","active");
INSERT INTO `products` VALUES(6900,29,"mumanga, (mi-)","manguier","_","active");
INSERT INTO `products` VALUES(6901,29,"munadzi, (mi-)","cocotier","_","active");
INSERT INTO `products` VALUES(6902,29,"mupambafuma, (mi-)","kapokier","_","active");
INSERT INTO `products` VALUES(6903,29,"mupapaya, (mi-)","papayer","_","active");
INSERT INTO `products` VALUES(6904,29,"mupwera, (mi-)","goyavier","_","active");
INSERT INTO `products` VALUES(6905,29,"murendre, (mi-)","palmier","_","active");
INSERT INTO `products` VALUES(6906,29,"murundra, (mi-)","oranger","_","active");
INSERT INTO `products` VALUES(6907,29,"murundra-pevoni, (mi-)","grenadier","_","active");
INSERT INTO `products` VALUES(6908,29,"muvovoo, (mi-)","arequier","_","active");
INSERT INTO `products` VALUES(6909,29,"muwa, (miya)","canne à sucre","_","active");
INSERT INTO `products` VALUES(6910,29,"mvangati, (mi-)","raphia","_","active");
INSERT INTO `products` VALUES(6911,29,"mwiri, (miri)","arbre","_","active");
INSERT INTO `products` VALUES(6912,29,"myamba, (mi-)","badamier","_","active");
INSERT INTO `products` VALUES(6913,29,"mzambarawo, (mi-)","prunier","_","active");
INSERT INTO `products` VALUES(6914,29,"mzavuka, (mi-)","avocatier","_","active");
INSERT INTO `products` VALUES(6915,29,"trindri, (marindri)","bananier","_","active");
INSERT INTO `products` VALUES(6916,36,"bega (ma-)","épaule","_","active");
INSERT INTO `products` VALUES(6917,36,"bele (ma-)","sein","_","active");
INSERT INTO `products` VALUES(6918,36,"dzivuzi (mavuzi)","poil","_","active");
INSERT INTO `products` VALUES(6919,36,"kapwa (ma-)","aisselle","_","active");
INSERT INTO `products` VALUES(6920,36,"mbavu","côte","_","active");
INSERT INTO `products` VALUES(6921,36,"mba wa mengo","colonne vertébrale","_","active");
INSERT INTO `products` VALUES(6922,36,"mbo","pénis","_","active");
INSERT INTO `products` VALUES(6923,36,"mengo","dos","_","active");
INSERT INTO `products` VALUES(6924,36,"mimba","ventre","_","active");
INSERT INTO `products` VALUES(6925,36,"muvumo (mi-)","fesse","_","active");
INSERT INTO `products` VALUES(6926,36,"mwili (mili)","corps","_","active");
INSERT INTO `products` VALUES(6927,36,"ndzini / wadzi","vagin","_","active");
INSERT INTO `products` VALUES(6928,36,"ndzu","derrière","_","active");
INSERT INTO `products` VALUES(6929,36,"ngwezi","peau","_","active");
INSERT INTO `products` VALUES(6930,36,"nyama","chair","_","active");
INSERT INTO `products` VALUES(6931,36,"shifuba (zi-)","poitrine / torse","_","active");
INSERT INTO `products` VALUES(6932,36,"shiga (zi-)","membre","_","active");
INSERT INTO `products` VALUES(6933,36,"shihoho (zi-)","région lombaire, reins","_","active");
INSERT INTO `products` VALUES(6934,36,"shilepe (zi-)","clitoris","_","active");
INSERT INTO `products` VALUES(6935,36,"shinana (zi-)","pubis / bas ventre","_","active");
INSERT INTO `products` VALUES(6936,36,"shitswa (zi-)","tête","_","active");
INSERT INTO `products` VALUES(6937,36,"trenga (marenga)","bassin / hanches","_","active");
INSERT INTO `products` VALUES(6938,36,"tsingo","cou","_","active");
INSERT INTO `products` VALUES(6939,36,"umiyo (maumiyo)","gorge / gosier","_","active");
INSERT INTO `products` VALUES(6940,36,"domo (malomo)","lèvre","_","active");
INSERT INTO `products` VALUES(6941,36,"domo la uju","lèvre supérieure","_","active");
INSERT INTO `products` VALUES(6942,36,"domo la utsini","lèvre inférieure","_","active");
INSERT INTO `products` VALUES(6943,36,"duli (maluli)","gencive","_","active");
INSERT INTO `products` VALUES(6944,36,"dzinyo (manyo)","dent","_","active");
INSERT INTO `products` VALUES(6945,36,"dzitso (matso)","ϣil (yeux)","_","active");
INSERT INTO `products` VALUES(6946,36,"gãndzi (mahãndzi)","gorge","_","active");
INSERT INTO `products` VALUES(6947,36,"hanyo","bouche","_","active");
INSERT INTO `products` VALUES(6948,36,"kio (ma-)","oreille","_","active");
INSERT INTO `products` VALUES(6949,36,"kombe ya dzitso","paupière","_","active");
INSERT INTO `products` VALUES(6950,36,"komo (ma-)","front","_","active");
INSERT INTO `products` VALUES(6951,36,"kove","paupière, cil","_","active");
INSERT INTO `products` VALUES(6952,36,"ndrevu","barbe","_","active");
INSERT INTO `products` VALUES(6953,36,"nyele / nyole","cheveux","_","active");
INSERT INTO `products` VALUES(6954,36,"pembe","narine","_","active");
INSERT INTO `products` VALUES(6955,36,"pua","nez","_","active");
INSERT INTO `products` VALUES(6956,36,"savu (ma-)","joue","_","active");
INSERT INTO `products` VALUES(6957,36,"shilevu (zi-)","menton","_","active");
INSERT INTO `products` VALUES(6958,36,"sura","visage","_","active");
INSERT INTO `products` VALUES(6959,36,"tsawa","mâchoire","_","active");
INSERT INTO `products` VALUES(6960,36,"tsi / ntsi","sourcil","_","active");
INSERT INTO `products` VALUES(6961,36,"ulime (ma-)","langue","_","active");
INSERT INTO `products` VALUES(6962,36,"uso (ma-)","visage, front","_","active");
INSERT INTO `products` VALUES(6963,36,"djandza (ma-)","paume","_","active");
INSERT INTO `products` VALUES(6964,36,"dondro (malondro)","genou","_","active");
INSERT INTO `products` VALUES(6965,36,"dzitso la pwedza","cheville","_","active");
INSERT INTO `products` VALUES(6966,36,"karo (ma-)","plante du pied","_","active");
INSERT INTO `products` VALUES(6967,36,"kofu (mahofu)","ongle","_","active");
INSERT INTO `products` VALUES(6968,36,"ma","ensemble des doigts","_","active");
INSERT INTO `products` VALUES(6969,36,"muhono (mi-)","bras / main","_","active");
INSERT INTO `products` VALUES(6970,36,"muhono wa kume","la main droite","_","active");
INSERT INTO `products` VALUES(6971,36,"muhono wa potro","la main gauche","_","active");
INSERT INTO `products` VALUES(6972,36,"mundru (mi-)","pied / jambe","_","active");
INSERT INTO `products` VALUES(6973,36,"paja (mavaja)","cuisse","_","active");
INSERT INTO `products` VALUES(6974,36,"sha (za / zisha)","doigt","_","active");
INSERT INTO `products` VALUES(6975,36,"sha ya koo","pouce","_","active");
INSERT INTO `products` VALUES(6976,36,"sha ya shahada","index","_","active");
INSERT INTO `products` VALUES(6977,36,"sha ya hari","majeur / médius","_","active");
INSERT INTO `products` VALUES(6978,36,"sha ya pere","annulaire","_","active");
INSERT INTO `products` VALUES(6979,36,"sha ya pwitsi / ya mwana","auriculaire","_","active");
INSERT INTO `products` VALUES(6980,36,"sha ya mundru","orteil / doigt de pied","_","active");
INSERT INTO `products` VALUES(6981,36,"shifungo (zi-)","poignet / articulation","_","active");
INSERT INTO `products` VALUES(6982,36,"tsoma","poing","_","active");
INSERT INTO `products` VALUES(6983,36,"tsundzuni","coude","_","active");
INSERT INTO `products` VALUES(6984,36,"damu","sang","_","active");
INSERT INTO `products` VALUES(6985,36,"hari","sueur","_","active");
INSERT INTO `products` VALUES(6986,36,"mare","salive","_","active");
INSERT INTO `products` VALUES(6987,36,"marumbo","intestins","_","active");
INSERT INTO `products` VALUES(6988,36,"matsozi","larmes","_","active");
INSERT INTO `products` VALUES(6989,36,"mo / roho","cœur","_","active");
INSERT INTO `products` VALUES(6990,36,"mpumu","respiration","_","active");
INSERT INTO `products` VALUES(6991,36,"mshipa (mizipa)","tendon","_","active");
INSERT INTO `products` VALUES(6992,36,"mubwa (mi-)","os","_","active");
INSERT INTO `products` VALUES(6993,36,"mwizi (mizi)","veine","_","active");
INSERT INTO `products` VALUES(6994,36,"ntso","rein","_","active");
INSERT INTO `products` VALUES(6995,36,"nye","foie","_","active");
INSERT INTO `products` VALUES(6996,36,"pumu","poumon(s)","_","active");
INSERT INTO `products` VALUES(6997,36,"pupu la roho (ma-)","battement de cœur","_","active");
INSERT INTO `products` VALUES(6998,36,"shiba (zi-)","côte, petit os","_","active");
INSERT INTO `products` VALUES(6999,36,"shombo sha mwili (z-)","organe","_","active");
INSERT INTO `products` VALUES(7000,36,"trumbo","estomac","_","active");
INSERT INTO `products` VALUES(7001,36,"wongo","cerveau","_","active");
INSERT INTO `products` VALUES(7002,36,"buhuo (ma-)","fièvre, rhume","_","active");
INSERT INTO `products` VALUES(7003,36,"dalao (malalao)","médicament","_","active");
INSERT INTO `products` VALUES(7004,36,"dalao lidarisao","calmant","_","active");
INSERT INTO `products` VALUES(7005,36,"dalao lihosao","désinfectant","_","active");
INSERT INTO `products` VALUES(7006,36,"homa","fièvre, température","_","active");
INSERT INTO `products` VALUES(7007,36,"kifafa","crise d'épilepsie","_","active");
INSERT INTO `products` VALUES(7008,36,"kolera","choléra","_","active");
INSERT INTO `products` VALUES(7009,36,"maradhi","maladie","_","active");
INSERT INTO `products` VALUES(7010,36,"mzusi (mi-)","panaris","_","active");
INSERT INTO `products` VALUES(7011,36,"pasima","pansement","_","active");
INSERT INTO `products` VALUES(7012,36,"pofu (ma-)","asthme","_","active");
INSERT INTO `products` VALUES(7013,36,"pomadi","pommade","_","active");
INSERT INTO `products` VALUES(7014,36,"shikali","guérison","_","active");
INSERT INTO `products` VALUES(7015,36,"shikodzo (zi-)","douleur","_","active");
INSERT INTO `products` VALUES(7016,36,"shikungunya","shikungunya","_","active");
INSERT INTO `products` VALUES(7017,36,"shitswa yaurwa","mal de tête","_","active");
INSERT INTO `products` VALUES(7018,36,"shiwi (zi-)","furoncle","_","active");
INSERT INTO `products` VALUES(7019,36,"shondra (zondra)","plaie, blessure","_","active");
INSERT INTO `products` VALUES(7020,36,"sida","sida","_","active");
INSERT INTO `products` VALUES(7021,36,"sindzano","piqûre, vaccin","_","active");
INSERT INTO `products` VALUES(7022,36,"unono","santé, bien-être","_","active");
INSERT INTO `products` VALUES(7023,36,"uwade wa sukari","diabète","_","active");
INSERT INTO `products` VALUES(7024,36,"bandi","bande","_","active");
INSERT INTO `products` VALUES(7025,36,"bloku","bloc chirurgical","_","active");
INSERT INTO `products` VALUES(7026,36,"dara","drap","_","active");
INSERT INTO `products` VALUES(7027,36,"dispenseri","dispensaire","_","active");
INSERT INTO `products` VALUES(7028,36,"duktera (ma-)","docteur","_","active");
INSERT INTO `products` VALUES(7029,36,"duktera wa makio","oto-rhyno-laryngologiste","_","active");
INSERT INTO `products` VALUES(7030,36,"duktera wa manyo","dentiste","_","active");
INSERT INTO `products` VALUES(7031,36,"duktera wa matso","ophtalmologue","_","active");
INSERT INTO `products` VALUES(7032,36,"duktera wa roho","cardiologue","_","active");
INSERT INTO `products` VALUES(7033,36,"farmasi","pharmacie","_","active");
INSERT INTO `products` VALUES(7034,36,"godoro (ma-)","matelas","_","active");
INSERT INTO `products` VALUES(7035,36,"labratwari","laboratoire","_","active");
INSERT INTO `products` VALUES(7036,36,"lapitali","hôpital","_","active");
INSERT INTO `products` VALUES(7037,36,"maternite","maternité","_","active");
INSERT INTO `products` VALUES(7038,36,"mudzalisa (wa-)","sage-femme","_","active");
INSERT INTO `products` VALUES(7039,36,"muwade (wa-)","malade, patient","_","active");
INSERT INTO `products` VALUES(7040,36,"opere","opération","_","active");
INSERT INTO `products` VALUES(7041,36,"pubeli","poubelle","_","active");
INSERT INTO `products` VALUES(7042,36,"shitrandra (zi-)","lit","_","active");
INSERT INTO `products` VALUES(7043,36,"siromu","sérum","_","active");
INSERT INTO `products` VALUES(7044,36,"twabibu (ma-)","médecin","_","active");
INSERT INTO `products` VALUES(7045,36,"twabibu alio dhwamana","médecin de garde","_","active");
INSERT INTO `products` VALUES(7046,36,"viziti","examen","_","active");
INSERT INTO `products` VALUES(7047,36,"zãfurmie","infirmière, infirmier","_","active");
INSERT INTO `products` VALUES(7048,36,"a muwade","il/elle est malade","_","active");
INSERT INTO `products` VALUES(7049,36,"adza","elle a accouché","_","active");
INSERT INTO `products` VALUES(7050,36,"adzihwa","il/elle est enterré","_","active");
INSERT INTO `products` VALUES(7051,36,"afu","il/elle est mort","_","active");
INSERT INTO `products` VALUES(7052,36,"alawa","il/elle est sorti","_","active");
INSERT INTO `products` VALUES(7053,36,"atrulia","il/elle est tranquille","_","active");
INSERT INTO `products` VALUES(7054,36,"avono","il/elle est guéri","_","active");
INSERT INTO `products` VALUES(7055,36,"bubu","muet","_","active");
INSERT INTO `products` VALUES(7056,36,"gudu (ma-) muhono","manchot","_","active");
INSERT INTO `products` VALUES(7057,36,"gudu (ma-) mundru","unijambiste","_","active");
INSERT INTO `products` VALUES(7058,36,"ina baridi","c'est froid","_","active");
INSERT INTO `products` VALUES(7059,36,"ina gazi","c'est gazeux","_","active");
INSERT INTO `products` VALUES(7060,36,"ina moro","c'est chaud","_","active");
INSERT INTO `products` VALUES(7061,36,"isihodza","ça fait mal","_","active");
INSERT INTO `products` VALUES(7062,36,"isiravisa","ça fait vomir","_","active");
INSERT INTO `products` VALUES(7063,36,"isirisidza","ça fait peur","_","active");
INSERT INTO `products` VALUES(7064,36,"isivona","ça guéri","_","active");
INSERT INTO `products` VALUES(7065,36,"isizimba","ça gonfle","_","active");
INSERT INTO `products` VALUES(7066,36,"mufumatso (wa-)","aveugle","_","active");
INSERT INTO `products` VALUES(7067,36,"mufumakio (wa-)","sourd","_","active");
INSERT INTO `products` VALUES(7068,36,"nisidridrima","je tremble","_","active");
INSERT INTO `products` VALUES(7069,36,"nisiona baridi","j'ai froid","_","active");
INSERT INTO `products` VALUES(7070,36,"nisiona udu","j'ai le vertige","_","active");
INSERT INTO `products` VALUES(7071,36,"nyama ha nyama","rapport sexuel non protégé","_","active");
INSERT INTO `products` VALUES(7072,36,"shiriwe (zi-)","handicapé","_","active");
INSERT INTO `products` VALUES(7073,36,"tsozi (ma-)","larme","_","active");
INSERT INTO `products` VALUES(7074,36,"ure (maure-)","bave, liquide séminal","_","active");
INSERT INTO `products` VALUES(7075,36,"-baya pumu","étouffer","_","active");
INSERT INTO `products` VALUES(7076,36,"-baya umiyo","étrangler","_","active");
INSERT INTO `products` VALUES(7077,36,"-endra mbio","palpiter","_","active");
INSERT INTO `products` VALUES(7078,36,"-fa","mourir","_","active");
INSERT INTO `products` VALUES(7079,36,"-fa maushe","être frigide","_","active");
INSERT INTO `products` VALUES(7080,36,"-gudzusa ishitswa","hocher la tête","_","active");
INSERT INTO `products` VALUES(7081,36,"-guguma","bégayer","_","active");
INSERT INTO `products` VALUES(7082,36,"-heana","faire l'amour","_","active");
INSERT INTO `products` VALUES(7083,36,"-hedza mabega","hausser les épaules","_","active");
INSERT INTO `products` VALUES(7084,36,"-hedza pumu","respirer","_","active");
INSERT INTO `products` VALUES(7085,36,"-hodza","être malade","_","active");
INSERT INTO `products` VALUES(7086,36,"-ka na mo","être vivant","_","active");
INSERT INTO `products` VALUES(7087,36,"-kawa","s'étouffer","_","active");
INSERT INTO `products` VALUES(7088,36,"-kodza","avoir mal","_","active");
INSERT INTO `products` VALUES(7089,36,"-kohola","tousser","_","active");
INSERT INTO `products` VALUES(7090,36,"-lawa hari","transpirer","_","active");
INSERT INTO `products` VALUES(7091,36,"-medza","avaler","_","active");
INSERT INTO `products` VALUES(7092,36,"-nya kojo","pisser / faire pipi","_","active");
INSERT INTO `products` VALUES(7093,36,"-nya madzi","déféquer / chier","_","active");
INSERT INTO `products` VALUES(7094,36,"-rema","battre","_","active");
INSERT INTO `products` VALUES(7095,36,"-samuha","s'étrangler","_","active");
INSERT INTO `products` VALUES(7096,36,"-sondza","sucer","_","active");
INSERT INTO `products` VALUES(7097,36,"-sondzeha","maigrir","_","active");
INSERT INTO `products` VALUES(7098,36,"-tahari","digérer","_","active");
INSERT INTO `products` VALUES(7099,36,"-tra mare","cracher","_","active");
INSERT INTO `products` VALUES(7100,36,"-tseha","rire / sourire","_","active");
INSERT INTO `products` VALUES(7101,36,"-vera imihono","se tourner les pouces","_","active");
INSERT INTO `products` VALUES(7102,36,"-vundza dondro","s'agenouiller","_","active");
INSERT INTO `products` VALUES(7103,35,"ndjeu","blanc","_","active");
INSERT INTO `products` VALUES(7104,35,"mosi, maingu","gris","_","active");
INSERT INTO `products` VALUES(7105,35,"ndzidu","noir","_","active");
INSERT INTO `products` VALUES(7106,35,"dzindzano, dzindzano bitsi","jaune","_","active");
INSERT INTO `products` VALUES(7107,35,"tamtamu","ocre, or","_","active");
INSERT INTO `products` VALUES(7108,35,"trundra, marundra, dzindzano lahiva","orange","_","active");
INSERT INTO `products` VALUES(7109,35,"ndzukundru","rouge","_","active");
INSERT INTO `products` VALUES(7110,35,"mawa","rose","_","active");
INSERT INTO `products` VALUES(7111,35,"zambarao","violet","_","active");
INSERT INTO `products` VALUES(7112,35,"bile kayahiva, maingu","bleu clair","_","active");
INSERT INTO `products` VALUES(7113,35,"bile","bleu","_","active");
INSERT INTO `products` VALUES(7114,35,"bile yahiva","bleu foncé","_","active");
INSERT INTO `products` VALUES(7115,35,"mani maitsi, mrututu kayahiva, malavu maitsi","vert clair","_","active");
INSERT INTO `products` VALUES(7116,35,"mrututu, davu, veri","vert","_","active");
INSERT INTO `products` VALUES(7117,35,"mani yahiva, mrututu yahiva, malavu yahiva","vert foncé","_","active");
INSERT INTO `products` VALUES(7118,35,"nye, shokola, trotro","brun, marron","_","active");
INSERT INTO `products` VALUES(7119,32,"daradja","niveau","_","active");
INSERT INTO `products` VALUES(7120,32,"kilasi","classe / niveau","_","active");
INSERT INTO `products` VALUES(7121,32,"koleji","collège","_","active");
INSERT INTO `products` VALUES(7122,32,"likoli","école","_","active");
INSERT INTO `products` VALUES(7123,32,"likoli bole","école primaire","_","active");
INSERT INTO `products` VALUES(7124,32,"lise","lycée","_","active");
INSERT INTO `products` VALUES(7125,32,"madarasa","école coranique","_","active");
INSERT INTO `products` VALUES(7126,32,"materneli","maternelle","_","active");
INSERT INTO `products` VALUES(7127,32,"seksio","section","_","active");
INSERT INTO `products` VALUES(7128,32,"fundi (ma-)","maître / professeur","_","active");
INSERT INTO `products` VALUES(7129,32,"mgalidzi (wa-)","surveillant","_","active");
INSERT INTO `products` VALUES(7130,32,"mtru wa hazi (wa-)","agent d'entretien","_","active");
INSERT INTO `products` VALUES(7131,32,"muhundza lakuru (wa-)","balayeur","_","active");
INSERT INTO `products` VALUES(7132,32,"muvia (wa-)","nouveau","_","active");
INSERT INTO `products` VALUES(7133,32,"mwanashioni (wanazioni)","élève","_","active");
INSERT INTO `products` VALUES(7134,32,"mwongozi (wa-)","principal","_","active");
INSERT INTO `products` VALUES(7135,32,"mwongozi wa vili","principal adjoint","_","active");
INSERT INTO `products` VALUES(7136,32,"bao","tableau","_","active");
INSERT INTO `products` VALUES(7137,32,"blanko","blanco","_","active");
INSERT INTO `products` VALUES(7138,32,"buku (ma-)","livre","_","active");
INSERT INTO `products` VALUES(7139,32,"fenetra","fenêtre","_","active");
INSERT INTO `products` VALUES(7140,32,"fetra (ma-)","feutre","_","active");
INSERT INTO `products` VALUES(7141,32,"gomu (ma-)","gomme","_","active");
INSERT INTO `products` VALUES(7142,32,"karatasi","feuille","_","active");
INSERT INTO `products` VALUES(7143,32,"kaye","cahier","_","active");
INSERT INTO `products` VALUES(7144,32,"kireyo","crayon","_","active");
INSERT INTO `products` VALUES(7145,32,"kompa","compas","_","active");
INSERT INTO `products` VALUES(7146,32,"lakire","craie","_","active");
INSERT INTO `products` VALUES(7147,32,"lakoli","colle","_","active");
INSERT INTO `products` VALUES(7148,32,"latabu","table","_","active");
INSERT INTO `products` VALUES(7149,32,"makasi","ciseaux","_","active");
INSERT INTO `products` VALUES(7150,32,"mukoba (mi-)","sac","_","active");
INSERT INTO `products` VALUES(7151,32,"mulongo","porte","_","active");
INSERT INTO `products` VALUES(7152,32,"mwenge","lumière","_","active");
INSERT INTO `products` VALUES(7153,32,"range","couleur","_","active");
INSERT INTO `products` VALUES(7154,32,"regili","règle","_","active");
INSERT INTO `products` VALUES(7155,32,"shifo","chiffon","_","active");
INSERT INTO `products` VALUES(7156,32,"shikandre (zi-)","page","_","active");
INSERT INTO `products` VALUES(7157,32,"shiri (zi-)","chaise","_","active");
INSERT INTO `products` VALUES(7158,32,"shombo ya hisabu","calculatrice","_","active");
INSERT INTO `products` VALUES(7159,32,"sitilo","stylo","_","active");
INSERT INTO `products` VALUES(7160,32,"vadilatera","ventilateur","_","active");
INSERT INTO `products` VALUES(7161,32,"wino","encre","_","active");
INSERT INTO `products` VALUES(7162,32,"djawabu","réponse","_","active");
INSERT INTO `products` VALUES(7163,32,"djitihadi","effort","_","active");
INSERT INTO `products` VALUES(7164,32,"fiziki","physique","_","active");
INSERT INTO `products` VALUES(7165,32,"hale","histoire","_","active");
INSERT INTO `products` VALUES(7166,32,"hisabu","maths","_","active");
INSERT INTO `products` VALUES(7167,32,"jeografi","géographie","_","active");
INSERT INTO `products` VALUES(7168,32,"kaulu (ma-)","mot","_","active");
INSERT INTO `products` VALUES(7169,32,"maeledzo","explication","_","active");
INSERT INTO `products` VALUES(7170,32,"miziki","musique","_","active");
INSERT INTO `products` VALUES(7171,32,"musomo (mi-)","leçon, cours","_","active");
INSERT INTO `products` VALUES(7172,32,"musomo wa maesha na dunia","SVT","_","active");
INSERT INTO `products` VALUES(7173,32,"shifarantsa","français","_","active");
INSERT INTO `products` VALUES(7174,32,"shimaore","mahorais","_","active");
INSERT INTO `products` VALUES(7175,32,"shimi","chimie","_","active");
INSERT INTO `products` VALUES(7176,32,"shingereza","anglais","_","active");
INSERT INTO `products` VALUES(7177,32,"sipori","sport / EPS","_","active");
INSERT INTO `products` VALUES(7178,32,"suala","question","_","active");
INSERT INTO `products` VALUES(7179,32,"ujuzi","connaissance","_","active");
INSERT INTO `products` VALUES(7180,32,"fahamu !","attention !","_","active");
INSERT INTO `products` VALUES(7181,32,"fanya djitihadi !","fait un effort !","_","active");
INSERT INTO `products` VALUES(7182,32,"fetre","bien","_","active");
INSERT INTO `products` VALUES(7183,32,"heya tablo !","va au tableau !","_","active");
INSERT INTO `products` VALUES(7184,32,"ipasuha","c'est cassé","_","active");
INSERT INTO `products` VALUES(7185,32,"irandruha","c'est déchiré","_","active");
INSERT INTO `products` VALUES(7186,32,"isitawi","c'est bon","_","active");
INSERT INTO `products` VALUES(7187,32,"iyo ndzuzuri","c'est joli","_","active");
INSERT INTO `products` VALUES(7188,32,"latsa shitru iyo !","jette ça !","_","active");
INSERT INTO `products` VALUES(7189,32,"maana yahe trini","définition","_","active");
INSERT INTO `products` VALUES(7190,32,"malambe","c'est môche","_","active");
INSERT INTO `products` VALUES(7191,32,"tsi fetre","ce n'est pas bien","_","active");
INSERT INTO `products` VALUES(7192,32,"vwa trotro","c'est sale","_","active");
INSERT INTO `products` VALUES(7193,32,"ya ndziro","c'est difficile","_","active");
INSERT INTO `products` VALUES(7194,32,"-ambia","dire","_","active");
INSERT INTO `products` VALUES(7195,32,"-dala","oublier","_","active");
INSERT INTO `products` VALUES(7196,32,"-djibu","répondre","_","active");
INSERT INTO `products` VALUES(7197,32,"-dzisa","demander","_","active");
INSERT INTO `products` VALUES(7198,32,"-eledza","expliquer","_","active");
INSERT INTO `products` VALUES(7199,32,"-elewa","comprendre","_","active");
INSERT INTO `products` VALUES(7200,32,"-endra likoli","aller à l'école","_","active");
INSERT INTO `products` VALUES(7201,32,"-fahamu","faire attention","_","active");
INSERT INTO `products` VALUES(7202,32,"-fanya","faire","_","active");
INSERT INTO `products` VALUES(7203,32,"-fundriha","apprendre (s')","_","active");
INSERT INTO `products` VALUES(7204,32,"-fungwa","être puni","_","active");
INSERT INTO `products` VALUES(7205,32,"-hangiha","écrire","_","active");
INSERT INTO `products` VALUES(7206,32,"-homa","être en retard","_","active");
INSERT INTO `products` VALUES(7207,32,"-jua","savoir","_","active");
INSERT INTO `products` VALUES(7208,32,"-ketsi","asseoir (s')","_","active");
INSERT INTO `products` VALUES(7209,32,"-kia","écouter","_","active");
INSERT INTO `products` VALUES(7210,32,"-lagua","parler","_","active");
INSERT INTO `products` VALUES(7211,32,"-ngalia","regarder","_","active");
INSERT INTO `products` VALUES(7212,32,"-regea","répéter","_","active");
INSERT INTO `products` VALUES(7213,32,"-shindra","réussir","_","active");
INSERT INTO `products` VALUES(7214,32,"-soma","lire / apprendre","_","active");
INSERT INTO `products` VALUES(7215,32,"-somedza / -somesa","enseigner","_","active");
INSERT INTO `products` VALUES(7216,32,"-twali","apprendre (par cœur)","_","active");
INSERT INTO `products` VALUES(7217,32,"-wanyisa","partager","_","active");
INSERT INTO `products` VALUES(7218,19,"baba (wa-)","papa, père","_","active");
INSERT INTO `products` VALUES(7219,19,"mama (wa-)","maman, mère","_","active");
INSERT INTO `products` VALUES(7220,19,"mudzade (wa-)","parent","_","active");
INSERT INTO `products` VALUES(7221,19,"mwanananya (wa-)","frère, soeur","_","active");
INSERT INTO `products` VALUES(7222,19,"mwanananya mtiti (wa-)","petit frère, petite soeur","_","active");
INSERT INTO `products` VALUES(7223,19,"mwanananya mtru-baba","frère","_","active");
INSERT INTO `products` VALUES(7224,19,"mwanananya mtru-mama","soeur","_","active");
INSERT INTO `products` VALUES(7225,19,"zuki (ma-)","frère ou soeur aîné","_","active");
INSERT INTO `products` VALUES(7226,19,"mwana (wa-)","enfant","_","active");
INSERT INTO `products` VALUES(7227,19,"mwana mtru-baba","garçon","_","active");
INSERT INTO `products` VALUES(7228,19,"mwana mtru-mama","fille","_","active");
INSERT INTO `products` VALUES(7229,19,"mwana zaza","bébé","_","active");
INSERT INTO `products` VALUES(7230,19,"mwanamtsa (wanatsa)","enfant, jeune","_","active");
INSERT INTO `products` VALUES(7231,19,"mwanamtsa mtru-baba","fils","_","active");
INSERT INTO `products` VALUES(7232,19,"mdjemaza (wa-)","parent, proche","_","active");
INSERT INTO `products` VALUES(7233,19,"koko (mahoko)","grand-mère","_","active");
INSERT INTO `products` VALUES(7234,19,"bakoko (ma-)","grand-père","_","active");
INSERT INTO `products` VALUES(7235,19,"mjuhu (wa-)","petit-fils, petite-fille","_","active");
INSERT INTO `products` VALUES(7236,19,"shilembwe (zi-)","arrière petit-enfant","_","active");
INSERT INTO `products` VALUES(7237,19,"zama (ma-)","oncle (maternel)","_","active");
INSERT INTO `products` VALUES(7238,19,"zena (ma-)","tante (épouse de zama)","_","active");
INSERT INTO `products` VALUES(7239,19,"ngivavi (ma-)","tante (paternelle)","_","active");
INSERT INTO `products` VALUES(7240,19,"bababole (wa-)","oncle (frère aîné du père)","_","active");
INSERT INTO `products` VALUES(7241,19,"babatiti (wa-)","oncle (frère cadet du père)","_","active");
INSERT INTO `products` VALUES(7242,19,"mamabole (wa-)","tante (soeur aînée de la mère)","_","active");
INSERT INTO `products` VALUES(7243,19,"mamatiti (wa-)","tante (soeur cadette de la mère)","_","active");
INSERT INTO `products` VALUES(7244,19,"bamuhe (wa-)","beau-frère","_","active");
INSERT INTO `products` VALUES(7245,19,"baba kambo","beau-père (mari de la mère)","_","active");
INSERT INTO `products` VALUES(7246,19,"mama kambo","marâtre, belle-mère (femme du père)","_","active");
INSERT INTO `products` VALUES(7247,19,"muha (wa-)","gendre, beau-père","_","active");
INSERT INTO `products` VALUES(7248,19,"mwamu (wa-)","belle-soeur","_","active");
INSERT INTO `products` VALUES(7249,19,"mwana haramu","enfant illégitime","_","active");
INSERT INTO `products` VALUES(7250,19,"mwana kambo","fils, fille du conjoint","_","active");
INSERT INTO `products` VALUES(7251,19,"mwananya wa baba mmoja","demi-frère, demi-soeur","_","active");
INSERT INTO `products` VALUES(7252,19,"nyadza","belle-mère","_","active");
INSERT INTO `products` VALUES(7253,19,"hirimu","classe d'âge","_","active");
INSERT INTO `products` VALUES(7254,19,"shababi (ma-)","jeune","_","active");
INSERT INTO `products` VALUES(7255,19,"mtsumba (wa-)","célibataire","_","active");
INSERT INTO `products` VALUES(7256,19,"unatsa","enfance","_","active");
INSERT INTO `products` VALUES(7257,19,"ushababi","jeunesse","_","active");
INSERT INTO `products` VALUES(7258,19,"uduhazi, ubakoko","vieillesse","_","active");
INSERT INTO `products` VALUES(7259,19,"ufa","la mort","_","active");
INSERT INTO `products` VALUES(7260,19,"mfu (wa-)","un mort","_","active");
INSERT INTO `products` VALUES(7261,19,"mudzade","parturiente","_","active");
INSERT INTO `products` VALUES(7262,19,"mutru-mama amira","femme enceinte","_","active");
INSERT INTO `products` VALUES(7263,19,"nguo za mwana","vêtements du bébé","_","active");
INSERT INTO `products` VALUES(7264,19,"arusi / harusi","mariage, noce","_","active");
INSERT INTO `products` VALUES(7265,19,"bibi arusi","la mariée","_","active");
INSERT INTO `products` VALUES(7266,19,"bwana arusi","le marié","_","active");
INSERT INTO `products` VALUES(7267,19,"karamu","festin, banquet","_","active");
INSERT INTO `products` VALUES(7268,19,"mafungidzo","acte de mariage","_","active");
INSERT INTO `products` VALUES(7269,19,"marumidzo","fiançailles","_","active");
INSERT INTO `products` VALUES(7270,19,"matsamiliyo","nuit de noce","_","active");
INSERT INTO `products` VALUES(7271,19,"mutru-baba (wa-)","homme","_","active");
INSERT INTO `products` VALUES(7272,19,"mutru-mama (wa-","femme","_","active");
INSERT INTO `products` VALUES(7273,19,"mutru-mme (wa- wa-)","époux, mari","_","active");
INSERT INTO `products` VALUES(7274,19,"mutru-mshe (wa- wa-)","épouse, femme","_","active");
INSERT INTO `products` VALUES(7275,19,"ndrola","mariage","_","active");
INSERT INTO `products` VALUES(7276,19,"shahidi (mazahidi)","témoin","_","active");
INSERT INTO `products` VALUES(7277,19,"twalaka","divorce","_","active");
INSERT INTO `products` VALUES(7278,19,"mwanamtsa muhali","enfant toujours dans les jupons de sa mère","_","active");
INSERT INTO `products` VALUES(7279,19,"watru-mama na watru-baba ra sawa","les femmes et les hommes, on est égal","_","active");
INSERT INTO `products` VALUES(7280,19,"udzaa","accoucher","_","active");
INSERT INTO `products` VALUES(7281,19,"upishia mudzade","cuisiner pour la parturiente","_","active");
INSERT INTO `products` VALUES(7282,19,"uva dzina mwana","donner un nom à l'enfant","_","active");
INSERT INTO `products` VALUES(7283,31,"banara","toit en terrasse","_","active");
INSERT INTO `products` VALUES(7284,31,"banga la upishia","cuisine","_","active");
INSERT INTO `products` VALUES(7285,31,"baraza (ma-)","véranda, terrasse","_","active");
INSERT INTO `products` VALUES(7286,31,"dao la kuhu","poulailler","_","active");
INSERT INTO `products` VALUES(7287,31,"dari","étage","_","active");
INSERT INTO `products` VALUES(7288,31,"fuko (ma-)","pièce, chambre","_","active");
INSERT INTO `products` VALUES(7289,31,"fuko la ulia","salle à manger","_","active");
INSERT INTO `products` VALUES(7290,31,"fuko la mtru-baba","chambre de garçon","_","active");
INSERT INTO `products` VALUES(7291,31,"fuko la mtru-mama","chambre de fille","_","active");
INSERT INTO `products` VALUES(7292,31,"fuko la wadjeni","salon","_","active");
INSERT INTO `products` VALUES(7293,31,"kanya","grenier","_","active");
INSERT INTO `products` VALUES(7294,31,"lakuru","cour","_","active");
INSERT INTO `products` VALUES(7295,31,"leskalye","escalier","_","active");
INSERT INTO `products` VALUES(7296,31,"mbaga","feuille tressée pour le toit","_","active");
INSERT INTO `products` VALUES(7297,31,"mtseve","feuille tressée pour la clôture","_","active");
INSERT INTO `products` VALUES(7298,31,"muraba","clôture","_","active");
INSERT INTO `products` VALUES(7299,31,"muraba wa sho","toilettes","_","active");
INSERT INTO `products` VALUES(7300,31,"neõ","néon","_","active");
INSERT INTO `products` VALUES(7301,31,"nyumba","maison","_","active");
INSERT INTO `products` VALUES(7302,31,"nyumba ya dari","maison à étage","_","active");
INSERT INTO `products` VALUES(7303,31,"parape","parpaing","_","active");
INSERT INTO `products` VALUES(7304,31,"pesi (mavesi)","mur, cloison","_","active");
INSERT INTO `products` VALUES(7305,31,"plafõ","plafond, toit","_","active");
INSERT INTO `products` VALUES(7306,31,"pombo (mavombo)","plafond","_","active");
INSERT INTO `products` VALUES(7307,31,"sakafu","plancher","_","active");
INSERT INTO `products` VALUES(7308,31,"shitasa (zi-)","verrou","_","active");
INSERT INTO `products` VALUES(7309,31,"sima","ciment","_","active");
INSERT INTO `products` VALUES(7310,31,"toli","tôle ondulé","_","active");
INSERT INTO `products` VALUES(7311,31,"uhanza","feuille pliée","_","active");
INSERT INTO `products` VALUES(7312,31,"ulingo","échelle","_","active");
INSERT INTO `products` VALUES(7313,31,"unyasi","chaume","_","active");
INSERT INTO `products` VALUES(7314,31,"utro","toit, toiture","_","active");
INSERT INTO `products` VALUES(7315,31,"bako la gazi","gazinière","_","active");
INSERT INTO `products` VALUES(7316,31,"bandrishio","chauffe-bain","_","active");
INSERT INTO `products` VALUES(7317,31,"bife","armoire","_","active");
INSERT INTO `products` VALUES(7318,31,"bife ya tele","meuble de télévision","_","active");
INSERT INTO `products` VALUES(7319,31,"dalo (malalo)","natte fine","_","active");
INSERT INTO `products` VALUES(7320,31,"djavi (ma-)","natte (pour les repas)","_","active");
INSERT INTO `products` VALUES(7321,31,"foteyi","fauteuil","_","active");
INSERT INTO `products` VALUES(7322,31,"frigo","réfrigérateur","_","active");
INSERT INTO `products` VALUES(7323,31,"kanape","canapé","_","active");
INSERT INTO `products` VALUES(7324,31,"kanape ya mwiri","canapé en bois","_","active");
INSERT INTO `products` VALUES(7325,31,"kitambaa","nappe, naperon","_","active");
INSERT INTO `products` VALUES(7326,31,"konjelatera","congélateur","_","active");
INSERT INTO `products` VALUES(7327,31,"mustakera","moustiquaire","_","active");
INSERT INTO `products` VALUES(7328,31,"muswala (mi-)","tapis de prière","_","active");
INSERT INTO `products` VALUES(7329,31,"mutsao wa kanape (mi-)","coussin","_","active");
INSERT INTO `products` VALUES(7330,31,"mutsao wa ulala (mi-)","oreiller","_","active");
INSERT INTO `products` VALUES(7331,31,"radio","poste de radio","_","active");
INSERT INTO `products` VALUES(7332,31,"rido","rideau","_","active");
INSERT INTO `products` VALUES(7333,31,"tapi","tapis","_","active");
INSERT INTO `products` VALUES(7334,31,"tele","télévision","_","active");
INSERT INTO `products` VALUES(7335,31,"fera ya upasi","fer à repasser","_","active");
INSERT INTO `products` VALUES(7336,31,"peo (maveo)","balais","_","active");
INSERT INTO `products` VALUES(7337,31,"ufanya mihare","faire des gâteaux","_","active");
INSERT INTO `products` VALUES(7338,31,"ufua","laver le linge","_","active");
INSERT INTO `products` VALUES(7339,31,"ufuma nguo","coudre les vêtements","_","active");
INSERT INTO `products` VALUES(7340,31,"ugaudza rido","changer les rideaux","_","active");
INSERT INTO `products` VALUES(7341,31,"uhodza latabu","mettre la table","_","active");
INSERT INTO `products` VALUES(7342,31,"uhodza shitrandra","faire le lit","_","active");
INSERT INTO `products` VALUES(7343,31,"uhosa nyungu","laver les marmites","_","active");
INSERT INTO `products` VALUES(7344,31,"uhosa sahani","laver la vaisselle","_","active");
INSERT INTO `products` VALUES(7345,31,"uhosa zia","faire la vaisselle","_","active");
INSERT INTO `products` VALUES(7346,31,"uhundza lakuru","balayer la cour","_","active");
INSERT INTO `products` VALUES(7347,31,"ukatra nyama","couper la viande","_","active");
INSERT INTO `products` VALUES(7348,31,"upasi nguo","repasser les vêtements","_","active");
INSERT INTO `products` VALUES(7349,31,"upiha","faire la cuisine","_","active");
INSERT INTO `products` VALUES(7350,31,"ureha maji","chercher de l'eau","_","active");
INSERT INTO `products` VALUES(7351,31,"usona","coudre","_","active");
INSERT INTO `products` VALUES(7352,31,"usuka","tresser","_","active");
INSERT INTO `products` VALUES(7353,31,"utahani nyama","hacher la viande","_","active");
INSERT INTO `products` VALUES(7354,31,"utria serpyeri","passer la serpillière","_","active");
INSERT INTO `products` VALUES(7355,31,"uvahua shahula","servir le repas","_","active");
INSERT INTO `products` VALUES(7356,31,"uvangua sahani","essuyer les assiettes","_","active");
INSERT INTO `products` VALUES(7357,31,"uvangusa fenetra","nettoyer les fenêtres","_","active");
INSERT INTO `products` VALUES(7358,31,"uvangusa mebli","épousseter les meubles","_","active");
INSERT INTO `products` VALUES(7359,31,"uvera dara","plier les drap","_","active");
INSERT INTO `products` VALUES(7360,31,"uvera nguo","plier les vêtements","_","active");
INSERT INTO `products` VALUES(7361,31,"benwari","baignoire","_","active");
INSERT INTO `products` VALUES(7362,31,"brosi","brosse","_","active");
INSERT INTO `products` VALUES(7363,31,"brosi ya mraba","brosse pour les WC","_","active");
INSERT INTO `products` VALUES(7364,31,"bwati ya farmasi","armoire à pharmacie","_","active");
INSERT INTO `products` VALUES(7365,31,"dalao la muswaki","dentifrice","_","active");
INSERT INTO `products` VALUES(7366,31,"dushu","douche","_","active");
INSERT INTO `products` VALUES(7367,31,"lavabo","lavabo","_","active");
INSERT INTO `products` VALUES(7368,31,"maji ya moro","chauffe-eau","_","active");
INSERT INTO `products` VALUES(7369,31,"marashi ya ndrevu","après-rasage","_","active");
INSERT INTO `products` VALUES(7370,31,"muswaki (mi-)","brosse à dent","_","active");
INSERT INTO `products` VALUES(7371,31,"papye ya mrabani","papier toilette","_","active");
INSERT INTO `products` VALUES(7372,31,"penye","peigne","_","active");
INSERT INTO `products` VALUES(7373,31,"razwari","rasoir","_","active");
INSERT INTO `products` VALUES(7374,31,"sabuni","savon","_","active");
INSERT INTO `products` VALUES(7375,31,"sanuo (ma-)","peigne en bois","_","active");
INSERT INTO `products` VALUES(7376,31,"sarvyeti","serviette","_","active");
INSERT INTO `products` VALUES(7377,31,"shampoin","shampoing","_","active");
INSERT INTO `products` VALUES(7378,31,"shido (zi-)","miroir","_","active");
INSERT INTO `products` VALUES(7379,31,"sindrasi","WC, latrines","_","active");
INSERT INTO `products` VALUES(7380,31,"sindrasi ya watru-baba","urinoir","_","active");
INSERT INTO `products` VALUES(7381,31,"fetre, alhamdulillahi !","bien, grâce à Dieu !","_","active");
INSERT INTO `products` VALUES(7382,31,"hairi !","très bien !","_","active");
INSERT INTO `products` VALUES(7383,31,"hodi ?","il y a quelqu'un ?","_","active");
INSERT INTO `products` VALUES(7384,31,"imenyeha","c'est abîmé","_","active");
INSERT INTO `products` VALUES(7385,31,"ina djifu","il y a de la poussière","_","active");
INSERT INTO `products` VALUES(7386,31,"isinuka fetre","ça sent bon","_","active");
INSERT INTO `products` VALUES(7387,31,"isinuka nayi","ça sent mauvais","_","active");
INSERT INTO `products` VALUES(7388,31,"jeje ?","comment ça va ?","_","active");
INSERT INTO `products` VALUES(7389,31,"karibu !","bienvenu !","_","active");
INSERT INTO `products` VALUES(7390,31,"ketsi !","assieds-toi !","_","active");
INSERT INTO `products` VALUES(7391,31,"murendre jeje ?","comment allez-vous ?","_","active");
INSERT INTO `products` VALUES(7392,31,"namuketsi !","asseyez-vous !","_","active");
INSERT INTO `products` VALUES(7393,31,"namungiye !","entrez !","_","active");
INSERT INTO `products` VALUES(7394,31,"njema !","bien !","_","active");
INSERT INTO `products` VALUES(7395,31,"tsilemewa","je suis fatigué","_","active");
INSERT INTO `products` VALUES(7396,31,"uhimi fetre","tu es bien réveillé","_","active");
INSERT INTO `products` VALUES(7397,31,"urendre jeje ?","comment vas-tu ?","_","active");
INSERT INTO `products` VALUES(7398,31,"vwa baridi","il fait froid","_","active");
INSERT INTO `products` VALUES(7399,31,"vwa hari","il fait chaud","_","active");
INSERT INTO `products` VALUES(7400,31,"-bala","fermer","_","active");
INSERT INTO `products` VALUES(7401,31,"-bua","ouvrir","_","active");
INSERT INTO `products` VALUES(7402,31,"-djihosa","se laver","_","active");
INSERT INTO `products` VALUES(7403,31,"-dudua","piler","_","active");
INSERT INTO `products` VALUES(7404,31,"-gaudza","changer","_","active");
INSERT INTO `products` VALUES(7405,31,"-aniha","étendre au soleil","_","active");
INSERT INTO `products` VALUES(7406,31,"-helesedza","réchauffer","_","active");
INSERT INTO `products` VALUES(7407,31,"-hoa","se baigner","_","active");
INSERT INTO `products` VALUES(7408,31,"-humisa","faire sécher","_","active");
INSERT INTO `products` VALUES(7409,31,"-hundza","balayer","_","active");
INSERT INTO `products` VALUES(7410,31,"-katra","couper","_","active");
INSERT INTO `products` VALUES(7411,31,"-lala","dormir","_","active");
INSERT INTO `products` VALUES(7412,31,"-lawa","sortir","_","active");
INSERT INTO `products` VALUES(7413,31,"-lodza","tremper","_","active");
INSERT INTO `products` VALUES(7414,31,"-mea ndrevu","se raser","_","active");
INSERT INTO `products` VALUES(7415,31,"-menya","abîmer","_","active");
INSERT INTO `products` VALUES(7416,31,"-ngiya","entrer","_","active");
INSERT INTO `products` VALUES(7417,31,"-nunua","acheter","_","active");
INSERT INTO `products` VALUES(7418,31,"-oha","griller","_","active");
INSERT INTO `products` VALUES(7419,31,"-patsa","allumer","_","active");
INSERT INTO `products` VALUES(7420,31,"-penye","se peigner","_","active");
INSERT INTO `products` VALUES(7421,31,"-piha","cuisiner","_","active");
INSERT INTO `products` VALUES(7422,31,"-rengeledza","ranger, arranger","_","active");
INSERT INTO `products` VALUES(7423,31,"-toa djifu","épousseter","_","active");
INSERT INTO `products` VALUES(7424,31,"-tsamba","se laver le derrière","_","active");
INSERT INTO `products` VALUES(7425,31,"-vaha","peindre","_","active");
INSERT INTO `products` VALUES(7426,31,"-vangusa","essuyer","_","active");
INSERT INTO `products` VALUES(7427,31,"-vinga","amener, apporter","_","active");
INSERT INTO `products` VALUES(7428,31,"-zima","éteindre","_","active");
INSERT INTO `products` VALUES(7429,31,"-zimba nyumba","couvrir une maison","_","active");
INSERT INTO `products` VALUES(7430,37,"bibo","noix de cajou","_","active");
INSERT INTO `products` VALUES(7431,37,"buyu","fruit du baobab","_","active");
INSERT INTO `products` VALUES(7432,37,"balandzi (mabalandzi)","mandarine","_","active");
INSERT INTO `products` VALUES(7433,37,"djoro","mangue mûre","_","active");
INSERT INTO `products` VALUES(7434,37,"fenesi (mafenesi)","jaque","_","active");
INSERT INTO `products` VALUES(7435,37,"frampe","fruit à pain","_","active");
INSERT INTO `products` VALUES(7436,37,"konokono (makonokono)","corossol","_","active");
INSERT INTO `products` VALUES(7437,37,"konokono matso","pomme cannelle","_","active");
INSERT INTO `products` VALUES(7438,37,"konokono miba","corossol épineux","_","active");
INSERT INTO `products` VALUES(7439,37,"konokono roho ya nyombe","cœur de bœuf","_","active");
INSERT INTO `products` VALUES(7440,37,"kumvava","combava","_","active");
INSERT INTO `products` VALUES(7441,37,"manga","mangue","_","active");
INSERT INTO `products` VALUES(7442,37,"nadzi","coco","_","active");
INSERT INTO `products` VALUES(7443,37,"nanasi (mananasi)","ananas","_","active");
INSERT INTO `products` VALUES(7444,37,"ndrimu","citron","_","active");
INSERT INTO `products` VALUES(7445,37,"ndrimu monye","citron vert","_","active");
INSERT INTO `products` VALUES(7446,37,"pomu","pomme","_","active");
INSERT INTO `products` VALUES(7447,37,"papaya / pwapwaya (ma-)","papaye","_","active");
INSERT INTO `products` VALUES(7448,37,"pwera (mavwera)","goyave","_","active");
INSERT INTO `products` VALUES(7449,37,"sakuwa","fruit du jévi","_","active");
INSERT INTO `products` VALUES(7450,37,"shijavu (zijavu)","coco à boire","_","active");
INSERT INTO `products` VALUES(7451,37,"sindza (masindza)","banane mûre","_","active");
INSERT INTO `products` VALUES(7452,37,"trango","melon","_","active");
INSERT INTO `products` VALUES(7453,37,"trango maji","pastèque","_","active");
INSERT INTO `products` VALUES(7454,37,"trendre","datte","_","active");
INSERT INTO `products` VALUES(7455,37,"trovi","banane verte","_","active");
INSERT INTO `products` VALUES(7456,37,"trundra LA pevoni","grenade","_","active");
INSERT INTO `products` VALUES(7457,37,"tsenavu","petit fruit jaune","_","active");
INSERT INTO `products` VALUES(7458,37,"uhaju","tamarin","_","active");
INSERT INTO `products` VALUES(7459,37,"uhaju wa shizungu","bilimbi","_","active");
INSERT INTO `products` VALUES(7460,37,"uhaju wa shihindi","carambole","_","active");
INSERT INTO `products` VALUES(7461,37,"zabibu","raisin","_","active");
INSERT INTO `products` VALUES(7462,37,"zavuka","avocat","_","active");
INSERT INTO `products` VALUES(7463,37,"batata","patate douce","_","active");
INSERT INTO `products` VALUES(7464,37,"bengani (mabengani)","aubergine","_","active");
INSERT INTO `products` VALUES(7465,37,"feliki (mafeliki)","brèdes","_","active");
INSERT INTO `products` VALUES(7466,37,"feliki majimbi","brèdes taro","_","active");
INSERT INTO `products` VALUES(7467,37,"feliki muhogo","brèdes manioc","_","active");
INSERT INTO `products` VALUES(7468,37,"jimbi (majimbi)","songe","_","active");
INSERT INTO `products` VALUES(7469,37,"karoti","carotte","_","active");
INSERT INTO `products` VALUES(7470,37,"kirison","cresson","_","active");
INSERT INTO `products` VALUES(7471,37,"kundre","haricots","_","active");
INSERT INTO `products` VALUES(7472,37,"lushu","chou","_","active");
INSERT INTO `products` VALUES(7473,37,"muhogo (mihogo)","manioc","_","active");
INSERT INTO `products` VALUES(7474,37,"murama (mirama)","maïs","_","active");
INSERT INTO `products` VALUES(7475,37,"pumditera","pomme de terre","_","active");
INSERT INTO `products` VALUES(7476,37,"putu (maputu)","piment","_","active");
INSERT INTO `products` VALUES(7477,37,"putu la shizungu","poivron","_","active");
INSERT INTO `products` VALUES(7478,37,"saladi","salade","_","active");
INSERT INTO `products` VALUES(7479,37,"shihazi (zihazi)","igname","_","active");
INSERT INTO `products` VALUES(7480,37,"shurungu","oignon","_","active");
INSERT INTO `products` VALUES(7481,37,"shurungu vuje","ail","_","active");
INSERT INTO `products` VALUES(7482,37,"tomati","tomate","_","active");
INSERT INTO `products` VALUES(7483,37,"tsandzi","lentilles","_","active");
INSERT INTO `products` VALUES(7484,37,"tsuzi","ambrevades","_","active");
INSERT INTO `products` VALUES(7485,37,"trango (marango)","citrouille","_","active");
INSERT INTO `products` VALUES(7486,37,"kokôbre","concombre","_","active");
INSERT INTO `products` VALUES(7487,37,"dzinzano","curcuma","_","active");
INSERT INTO `products` VALUES(7488,37,"hawadji","cumin","_","active");
INSERT INTO `products` VALUES(7489,37,"hiliki","cardamone","_","active");
INSERT INTO `products` VALUES(7490,37,"karafu","clou de girofle","_","active");
INSERT INTO `products` VALUES(7491,37,"kungumanga","noix de muscade","_","active");
INSERT INTO `products` VALUES(7492,37,"lavani","vanille","_","active");
INSERT INTO `products` VALUES(7493,37,"m'darasini (mi-)","cannelle","_","active");
INSERT INTO `products` VALUES(7494,37,"m'kadi (mi-)","basilic","_","active");
INSERT INTO `products` VALUES(7495,37,"singiziu","gingembre","_","active");
INSERT INTO `products` VALUES(7496,37,"vili vili","poivre","_","active");
INSERT INTO `products` VALUES(7497,37,"zaãfarani","safran","_","active");
INSERT INTO `products` VALUES(7498,37,"dipe","pain","_","active");
INSERT INTO `products` VALUES(7499,37,"dite / tshai","thé","_","active");
INSERT INTO `products` VALUES(7500,37,"dziya","lait","_","active");
INSERT INTO `products` VALUES(7501,37,"dziya lafa","lait caillé","_","active");
INSERT INTO `products` VALUES(7502,37,"fi","poisson","_","active");
INSERT INTO `products` VALUES(7503,37,"jwayi (majwayi)","œuf","_","active");
INSERT INTO `products` VALUES(7504,37,"kafe","café","_","active");
INSERT INTO `products` VALUES(7505,37,"kuhu","poulet","_","active");
INSERT INTO `products` VALUES(7506,37,"maji","eau","_","active");
INSERT INTO `products` VALUES(7507,37,"maji ya nadzi","lait de coco","_","active");
INSERT INTO `products` VALUES(7508,37,"matra","huile","_","active");
INSERT INTO `products` VALUES(7509,37,"matra ya nadzi","huile de coco","_","active");
INSERT INTO `products` VALUES(7510,37,"ngano","farine","_","active");
INSERT INTO `products` VALUES(7511,37,"ngizi","miel","_","active");
INSERT INTO `products` VALUES(7512,37,"ntsohole / tsohole","riz","_","active");
INSERT INTO `products` VALUES(7513,37,"penatsi","cacahuète, arachide","_","active");
INSERT INTO `products` VALUES(7514,37,"pwedza","poulpe","_","active");
INSERT INTO `products` VALUES(7515,37,"samuli","margarine, beurre","_","active");
INSERT INTO `products` VALUES(7516,37,"shingo","sel","_","active");
INSERT INTO `products` VALUES(7517,37,"shingo mjiva","glutamate","_","active");
INSERT INTO `products` VALUES(7518,37,"siki","vinaigre","_","active");
INSERT INTO `products` VALUES(7519,37,"sukari","sucre","_","active");
INSERT INTO `products` VALUES(7520,37,"tshari","achards","_","active");
INSERT INTO `products` VALUES(7521,37,"ushi","alcool","_","active");
INSERT INTO `products` VALUES(7522,37,"vinyo","vin","_","active");
INSERT INTO `products` VALUES(7523,37,"batabata","banane ou manioc bouilli","_","active");
INSERT INTO `products` VALUES(7524,37,"batabata la majimbi","songe bouilli","_","active");
INSERT INTO `products` VALUES(7525,37,"beredre","galette pimentée","_","active");
INSERT INTO `products` VALUES(7526,37,"bilingani ya nadzi","aubergine au coco","_","active");
INSERT INTO `products` VALUES(7527,37,"fi ya nadzi","poisson au coco","_","active");
INSERT INTO `products` VALUES(7528,37,"fi ya tomati","poisson à la tomate","_","active");
INSERT INTO `products` VALUES(7529,37,"frampe la viswa","fruit à pain frit","_","active");
INSERT INTO `products` VALUES(7530,37,"gulagula","gâteau, beignet","_","active");
INSERT INTO `products` VALUES(7531,37,"halua","haloua","_","active");
INSERT INTO `products` VALUES(7532,37,"kuhu ya tomati na drimu","poulet à la tomate et au citron","_","active");
INSERT INTO `products` VALUES(7533,37,"mabawa","ailes de poulet","_","active");
INSERT INTO `products` VALUES(7534,37,"mataba","brède manioc","_","active");
INSERT INTO `products` VALUES(7535,37,"matsidza","plat de riz blanc","_","active");
INSERT INTO `products` VALUES(7536,37,"mavaja","cuisses de poulet","_","active");
INSERT INTO `products` VALUES(7537,37,"mbuzi ya masala","cabri massalé","_","active");
INSERT INTO `products` VALUES(7538,37,"mshakiki (mishakiki)","viande grillée en brochette","_","active");
INSERT INTO `products` VALUES(7539,37,"mtsuzi (mitsuzi)","sauce, carri","_","active");
INSERT INTO `products` VALUES(7540,37,"mtsuzi wa baribari","carri de mouton","_","active");
INSERT INTO `products` VALUES(7541,37,"mtsuzi wa kuhu","carri de poulet","_","active");
INSERT INTO `products` VALUES(7542,37,"mtsuzi wa maji","sauce claire","_","active");
INSERT INTO `products` VALUES(7543,37,"mtsuzi wa matra","sauce à l'huile","_","active");
INSERT INTO `products` VALUES(7544,37,"mtsuzi wa mbuzi","cabri en sauce","_","active");
INSERT INTO `products` VALUES(7545,37,"mtsuzi wa nadzi","sauce au coco","_","active");
INSERT INTO `products` VALUES(7546,37,"mtsuzi wa nyombe","carri de boeuf","_","active");
INSERT INTO `products` VALUES(7547,37,"muhare (mihare)","gâteau, galette","_","active");
INSERT INTO `products` VALUES(7548,37,"mtsolola","banane ou manioc au citron","_","active");
INSERT INTO `products` VALUES(7549,37,"mtsolola ya fi","mtsolola au poisson","_","active");
INSERT INTO `products` VALUES(7550,37,"mtsolola ya nyama","mtsolola à la viande","_","active");
INSERT INTO `products` VALUES(7551,37,"ntsohole ya nadzi","riz au coco","_","active");
INSERT INTO `products` VALUES(7552,37,"pampa ya masala","requin aux épices","_","active");
INSERT INTO `products` VALUES(7553,37,"pangu","croûte de riz","_","active");
INSERT INTO `products` VALUES(7554,37,"pilau ya kuhu","riz pilaf au poulet","_","active");
INSERT INTO `products` VALUES(7555,37,"pilau ya nyama","riz pilaf à la viande","_","active");
INSERT INTO `products` VALUES(7556,37,"sambusa","samboussa, samossa","_","active");
INSERT INTO `products` VALUES(7557,37,"shandra","omelette","_","active");
INSERT INTO `products` VALUES(7558,37,"shireo (zireo)","viande, poisson, brèdes","_","active");
INSERT INTO `products` VALUES(7559,37,"tambi","vermicelle cuit au sucre","_","active");
INSERT INTO `products` VALUES(7560,37,"trovi ya nadzi","bananes au coco","_","active");
INSERT INTO `products` VALUES(7561,37,"tsuzi ya nadzi","ambrevades au coco","_","active");
INSERT INTO `products` VALUES(7562,37,"vule","grillade, barbecue","_","active");
INSERT INTO `products` VALUES(7563,37,"bakuli","bol","_","active");
INSERT INTO `products` VALUES(7564,37,"bwe (mawe)","pierre","_","active");
INSERT INTO `products` VALUES(7565,37,"difu","tamis","_","active");
INSERT INTO `products` VALUES(7566,37,"fursheti (ma-)","fourchette","_","active");
INSERT INTO `products` VALUES(7567,37,"kopo","récipient (pour l'eau)","_","active");
INSERT INTO `products` VALUES(7568,37,"kuveti (ma-)","cuvette","_","active");
INSERT INTO `products` VALUES(7569,37,"legeni","moule à gâteau","_","active");
INSERT INTO `products` VALUES(7570,37,"mbuzi ya nadzi","râpe à coco","_","active");
INSERT INTO `products` VALUES(7571,37,"moro","feu","_","active");
INSERT INTO `products` VALUES(7572,37,"moro mtiti","feu doux","_","active");
INSERT INTO `products` VALUES(7573,37,"mutsi (mi-)","pilon","_","active");
INSERT INTO `products` VALUES(7574,37,"nyungu","marmite","_","active");
INSERT INTO `products` VALUES(7575,37,"sembeya (ma-)","couteau","_","active");
INSERT INTO `products` VALUES(7576,37,"sadu","louche","_","active");
INSERT INTO `products` VALUES(7577,37,"sahani","assiette","_","active");
INSERT INTO `products` VALUES(7578,37,"shano (zano)","assiette en bois","_","active");
INSERT INTO `products` VALUES(7579,37,"siniya","plat","_","active");
INSERT INTO `products` VALUES(7580,37,"shia (zia)","vaisselle, assiettes","_","active");
INSERT INTO `products` VALUES(7581,37,"shikombe (zikombe)","tasse","_","active");
INSERT INTO `products` VALUES(7582,37,"shino (zino)","mortier","_","active");
INSERT INTO `products` VALUES(7583,37,"shiwi (ziwi)","louche pour goûter","_","active");
INSERT INTO `products` VALUES(7584,37,"sutru (ma-)","cuillère","_","active");
INSERT INTO `products` VALUES(7585,37,"sutru bole","cuillère à soupe","_","active");
INSERT INTO `products` VALUES(7586,37,"sutru titi","cuillère à café","_","active");
INSERT INTO `products` VALUES(7587,37,"tasa","poêle","_","active");
INSERT INTO `products` VALUES(7588,37,"tsari","assiette en terre","_","active");
INSERT INTO `products` VALUES(7589,37,"uhombe","cuillère en bois","_","active");
INSERT INTO `products` VALUES(7590,37,"vera","verre","_","active");
INSERT INTO `products` VALUES(7591,37,"ihivu","c'est cuit","_","active");
INSERT INTO `products` VALUES(7592,37,"ina ladha","ça a du goût","_","active");
INSERT INTO `products` VALUES(7593,37,"ina putu","c'est pimenté","_","active");
INSERT INTO `products` VALUES(7594,37,"ishia shingo","c'est trop salé","_","active");
INSERT INTO `products` VALUES(7595,37,"isijiva","c'est délicieux","_","active");
INSERT INTO `products` VALUES(7596,37,"izilia","c'est refroidi","_","active");
INSERT INTO `products` VALUES(7597,37,"kaina shingo","il n'y a pas de sel","_","active");
INSERT INTO `products` VALUES(7598,37,"kaisi ndjema","ce n'est pas bon","_","active");
INSERT INTO `products` VALUES(7599,37,"kali (manga kali)","acide (mangue acide)","_","active");
INSERT INTO `products` VALUES(7600,37,"madedzo","goinfrerie (avant le ramadan)","_","active");
INSERT INTO `products` VALUES(7601,37,"ya mbitsi","c'est cru, c'est vert","_","active");
INSERT INTO `products` VALUES(7602,37,"ya mbwadza","c'est fade","_","active");
INSERT INTO `products` VALUES(7603,37,"udedza","se goinfrer","_","active");
INSERT INTO `products` VALUES(7604,37,"uhedza","lever (pour la pâte)","_","active");
INSERT INTO `products` VALUES(7605,37,"uhiva","cuire","_","active");
INSERT INTO `products` VALUES(7606,37,"uhosa","laver, nettoyer","_","active");
INSERT INTO `products` VALUES(7607,37,"uhua","éplucher","_","active");
INSERT INTO `products` VALUES(7608,37,"uhua nadzi","râper la noix de coco","_","active");
INSERT INTO `products` VALUES(7609,37,"ukura","être rassasié","_","active");
INSERT INTO `products` VALUES(7610,37,"unwa","boire","_","active");
INSERT INTO `products` VALUES(7611,37,"uoha","griller, rôtir","_","active");
INSERT INTO `products` VALUES(7612,37,"uona ndza","avoir faim","_","active");
INSERT INTO `products` VALUES(7613,37,"uona nyora","avoir soif","_","active");
INSERT INTO `products` VALUES(7614,37,"upatsa putu","tremper dans du piment","_","active");
INSERT INTO `products` VALUES(7615,37,"urema vule","faire griller","_","active");
INSERT INTO `products` VALUES(7616,37,"urohora","bouillir","_","active");
INSERT INTO `products` VALUES(7617,37,"usinya","pétrir","_","active");
INSERT INTO `products` VALUES(7618,37,"utahani","hacher","_","active");
INSERT INTO `products` VALUES(7619,37,"utria","mettre, verser","_","active");
INSERT INTO `products` VALUES(7620,37,"utria bakoni","mettre au four","_","active");
INSERT INTO `products` VALUES(7621,37,"utria ndrimu","ajouter du citron","_","active");
INSERT INTO `products` VALUES(7622,37,"utsana","mâcher","_","active");
INSERT INTO `products` VALUES(7623,37,"utsanganisa","mélanger","_","active");
INSERT INTO `products` VALUES(7624,37,"utsera","écraser","_","active");
INSERT INTO `products` VALUES(7625,37,"uvala","écailler","_","active");
INSERT INTO `products` VALUES(7626,37,"uvalisa","émincer","_","active");
INSERT INTO `products` VALUES(7627,37,"uvisa","frire","_","active");
INSERT INTO `products` VALUES(7628,37,"uvudza moro","allumer le feu","_","active");
INSERT INTO `products` VALUES(7629,37,"uvuhura","croquer","_","active");
INSERT INTO `products` VALUES(7630,33,"lapeli","pelle","_","active");
INSERT INTO `products` VALUES(7631,33,"lapiki","pic","_","active");
INSERT INTO `products` VALUES(7632,33,"mupanga (mi-)","sabre, machette","_","active");
INSERT INTO `products` VALUES(7633,33,"mupira (mi-)","tuyau","_","active");
INSERT INTO `products` VALUES(7634,33,"mushari (mi-)","scie","_","active");
INSERT INTO `products` VALUES(7635,33,"mshumari (mizumari)","clou","_","active");
INSERT INTO `products` VALUES(7636,33,"ngandi","faucille","_","active");
INSERT INTO `products` VALUES(7637,33,"nyindro","marteau","_","active");
INSERT INTO `products` VALUES(7638,33,"shamburu (z-)","tenailles","_","active");
INSERT INTO `products` VALUES(7639,33,"shirumba (zi-)","panier en feuilles de cocotier","_","active");
INSERT INTO `products` VALUES(7640,33,"shombo (zombo)","coupe-coupe","_","active");
INSERT INTO `products` VALUES(7641,33,"shombo gori","coupe-coupe avec crochet","_","active");
INSERT INTO `products` VALUES(7642,33,"shombo pidja","coupe-coupe sans crochet","_","active");
INSERT INTO `products` VALUES(7643,33,"rato","râteau","_","active");
INSERT INTO `products` VALUES(7644,33,"soha","hache","_","active");
INSERT INTO `products` VALUES(7645,33,"mlimaji (wa-)","cultivateur","_","active");
INSERT INTO `products` VALUES(7646,33,"mlozi (wa-)","pêcheur","_","active");
INSERT INTO `products` VALUES(7647,33,"mutsunga (wa-)","éleveur","_","active");
INSERT INTO `products` VALUES(7648,33,"mutsunga baribari","éleveur de moutons","_","active");
INSERT INTO `products` VALUES(7649,33,"mutsunga mbuzi","éleveur de chèvres","_","active");
INSERT INTO `products` VALUES(7650,33,"mutsunga nyombe","éleveur de vaches","_","active");
INSERT INTO `products` VALUES(7651,33,"-bubua","battre le riz","_","active");
INSERT INTO `products` VALUES(7652,33,"-fitsiya","combler","_","active");
INSERT INTO `products` VALUES(7653,33,"-kokotsa","désherber","_","active");
INSERT INTO `products` VALUES(7654,33,"-lima","cultiver","_","active");
INSERT INTO `products` VALUES(7655,33,"-pasua kuni","couper du bois","_","active");
INSERT INTO `products` VALUES(7656,33,"-pua","cueillir","_","active");
INSERT INTO `products` VALUES(7657,33,"-tabu","planter","_","active");
INSERT INTO `products` VALUES(7658,33,"-tsimba","creuser","_","active");
INSERT INTO `products` VALUES(7659,33,"-vuna","récolter","_","active");
INSERT INTO `products` VALUES(7660,38,"djuba","djellaba","_","active");
INSERT INTO `products` VALUES(7661,38,"gondra (ma-)","boubou","_","active");
INSERT INTO `products` VALUES(7662,38,"goshi (ma-)","chaussure","_","active");
INSERT INTO `products` VALUES(7663,38,"hofu (ma-)","chaussette","_","active");
INSERT INTO `products` VALUES(7664,38,"kabwa","savate, tong","_","active");
INSERT INTO `products` VALUES(7665,38,"kaliso","caleçon, short","_","active");
INSERT INTO `products` VALUES(7666,38,"kandzu","robe pour homme","_","active");
INSERT INTO `products` VALUES(7667,38,"karavati","cravate","_","active");
INSERT INTO `products` VALUES(7668,38,"kofia (ma-)","chapeau","_","active");
INSERT INTO `products` VALUES(7669,38,"kofia kazi","chéchia blanche","_","active");
INSERT INTO `products` VALUES(7670,38,"kofia sitambule","chéchia rouge, fez","_","active");
INSERT INTO `products` VALUES(7671,38,"kofia ya mkirini","chapeau musulman","_","active");
INSERT INTO `products` VALUES(7672,38,"kotri (mahotri)","costume","_","active");
INSERT INTO `products` VALUES(7673,38,"mharuma","écharpe","_","active");
INSERT INTO `products` VALUES(7674,38,"mihono","manches","_","active");
INSERT INTO `products` VALUES(7675,38,"mkandra (mi-)","ceinture","_","active");
INSERT INTO `products` VALUES(7676,38,"tsahaya","fripes","_","active");
INSERT INTO `products` VALUES(7677,38,"shemizi","chemise","_","active");
INSERT INTO `products` VALUES(7678,38,"shemizi ya mihono miundra","chemise à manches longues","_","active");
INSERT INTO `products` VALUES(7679,38,"shitamba (zi-)","pagne d'homme","_","active");
INSERT INTO `products` VALUES(7680,38,"silipu","slip","_","active");
INSERT INTO `products` VALUES(7681,38,"sombrero","chapeau de paille","_","active");
INSERT INTO `products` VALUES(7682,38,"surwali","pantalon","_","active");
INSERT INTO `products` VALUES(7683,38,"triko","tricot, T-shirt","_","active");
INSERT INTO `products` VALUES(7684,38,"triko ya kapwani","débardeur","_","active");
INSERT INTO `products` VALUES(7685,38,"bodi","body","_","active");
INSERT INTO `products` VALUES(7686,38,"boksera","boxer","_","active");
INSERT INTO `products` VALUES(7687,38,"gawuni","robe, ensemble","_","active");
INSERT INTO `products` VALUES(7688,38,"jipo","jupe","_","active");
INSERT INTO `products` VALUES(7689,38,"jipo kutri","mini jupe","_","active");
INSERT INTO `products` VALUES(7690,38,"jipo ya buldjini","jupe en jean","_","active");
INSERT INTO `products` VALUES(7691,38,"jipo ya moni","jupon","_","active");
INSERT INTO `products` VALUES(7692,38,"kantshiri","soutien-gorge","_","active");
INSERT INTO `products` VALUES(7693,38,"kapisho","imperméable","_","active");
INSERT INTO `products` VALUES(7694,38,"kiloti","culotte","_","active");
INSERT INTO `products` VALUES(7695,38,"kishali","chàle","_","active");
INSERT INTO `products` VALUES(7696,38,"kolan","collant","_","active");
INSERT INTO `products` VALUES(7697,38,"magoshi ya mutru-mama","botte, basket pour fille","_","active");
INSERT INTO `products` VALUES(7698,38,"mayo","maillot de bain","_","active");
INSERT INTO `products` VALUES(7699,38,"mkandra wa mutru-mama","ceinture pour fille","_","active");
INSERT INTO `products` VALUES(7700,38,"mwavule","parapluie","_","active");
INSERT INTO `products` VALUES(7701,38,"nambawani","voile","_","active");
INSERT INTO `products` VALUES(7702,38,"nguo ya kapwa","vêtement à bretelles","_","active");
INSERT INTO `products` VALUES(7703,38,"patri (mavatri)","tissu","_","active");
INSERT INTO `products` VALUES(7704,38,"pipisi","chouchou","_","active");
INSERT INTO `products` VALUES(7705,38,"robo","robe","_","active");
INSERT INTO `products` VALUES(7706,38,"robo ya ulala","robe de nuit","_","active");
INSERT INTO `products` VALUES(7707,38,"saki ya muhono","sac à main","_","active");
INSERT INTO `products` VALUES(7708,38,"saluva","pagne de femme","_","active");
INSERT INTO `products` VALUES(7709,38,"shiromani","chiromani","_","active");
INSERT INTO `products` VALUES(7710,38,"stringili","string","_","active");
INSERT INTO `products` VALUES(7711,38,"surwali la burdjini","pantalon en jean","_","active");
INSERT INTO `products` VALUES(7712,38,"surwali la mutru-mama","pantalon pour femme","_","active");
INSERT INTO `products` VALUES(7713,38,"bavwari","bavoir","_","active");
INSERT INTO `products` VALUES(7714,38,"bibiro","biberon","_","active");
INSERT INTO `products` VALUES(7715,38,"foba za mwana","chaussettes","_","active");
INSERT INTO `products` VALUES(7716,38,"gari la mwana","poussette","_","active");
INSERT INTO `products` VALUES(7717,38,"kushu","couche","_","active");
INSERT INTO `products` VALUES(7718,38,"slipu ya mwana","slip d'enfant","_","active");
INSERT INTO `products` VALUES(7719,38,"titine","tétine","_","active");
INSERT INTO `products` VALUES(7720,38,"bangili","bracelet","_","active");
INSERT INTO `products` VALUES(7721,38,"bareti","barette","_","active");
INSERT INTO `products` VALUES(7722,38,"bwe la msindzano","tablier de corail utilisé pour faire le masque de beauté","_","active");
INSERT INTO `products` VALUES(7723,38,"dayiyo","parure","_","active");
INSERT INTO `products` VALUES(7724,38,"dhahabu","or","_","active");
INSERT INTO `products` VALUES(7725,38,"fedha","argent","_","active");
INSERT INTO `products` VALUES(7726,38,"gwena la ntsi","mascara","_","active");
INSERT INTO `products` VALUES(7727,38,"kame ya mdjeremani","grand collier qui couvre le corps","_","active");
INSERT INTO `products` VALUES(7728,38,"kavi","boucles d'oreille","_","active");
INSERT INTO `products` VALUES(7729,38,"kavi za dhahabu","boucles d'oreille en or","_","active");
INSERT INTO `products` VALUES(7730,38,"kuku ya dhahabu","bracelet en or","_","active");
INSERT INTO `products` VALUES(7731,38,"komba (mahomba)","masque de beauté","_","active");
INSERT INTO `products` VALUES(7732,38,"lulu","perle","_","active");
INSERT INTO `products` VALUES(7733,38,"mlala (mi-)","rouge à lèvre","_","active");
INSERT INTO `products` VALUES(7734,38,"montoro","montre","_","active");
INSERT INTO `products` VALUES(7735,38,"msindzano","bois de santal, masque de beauté","_","active");
INSERT INTO `products` VALUES(7736,38,"penye ya dhahabu","peigne en or","_","active");
INSERT INTO `products` VALUES(7737,38,"pere","bague","_","active");
INSERT INTO `products` VALUES(7738,38,"pere ya dhahabu","bague en or","_","active");
INSERT INTO `products` VALUES(7739,38,"sheni ya buruburu","chaîne ronde","_","active");
INSERT INTO `products` VALUES(7740,38,"sheni ya dhahabu","chaîne en or","_","active");
INSERT INTO `products` VALUES(7741,38,"sheredzo","encensoir en argile","_","active");
INSERT INTO `products` VALUES(7742,38,"shimamba","morceau de corail","_","active");
INSERT INTO `products` VALUES(7743,38,"shipini","bijou de nez","_","active");
INSERT INTO `products` VALUES(7744,38,"ubani","encens","_","active");
INSERT INTO `products` VALUES(7745,38,"imukiri swafi","ça lui va très bien","_","active");
INSERT INTO `products` VALUES(7746,38,"irahara","c'est propre","_","active");
INSERT INTO `products` VALUES(7747,38,"marandro","en haillons","_","active");
INSERT INTO `products` VALUES(7748,38,"upindra ha udziro","se mettre sur son 31","_","active");
INSERT INTO `products` VALUES(7749,38,"urahara swafi","tu es popre","_","active");
INSERT INTO `products` VALUES(7750,38,"ustawi","être élégant","_","active");
INSERT INTO `products` VALUES(7751,38,"ya bole ha nguvu na waye","c'est trop grand pour lui/elle","_","active");
INSERT INTO `products` VALUES(7752,38,"ya sawa sawa","c'est juste sa taille","_","active");
INSERT INTO `products` VALUES(7753,38,"ya titi ha nguvu na waye","c'est trop petit pour lui/elle","_","active");
INSERT INTO `products` VALUES(7754,38,"uhaniha","sécher au soleil","_","active");
INSERT INTO `products` VALUES(7755,38,"uhanua","retirer du soleil, ramasser","_","active");
INSERT INTO `products` VALUES(7756,38,"ujivisa","adorer, plaire","_","active");
INSERT INTO `products` VALUES(7757,38,"upara","trouver","_","active");
INSERT INTO `products` VALUES(7758,38,"upindra","s'habiller","_","active");
INSERT INTO `products` VALUES(7759,38,"upindrisa","habiller qq'un","_","active");
INSERT INTO `products` VALUES(7760,38,"urandrua","déchirer","_","active");
INSERT INTO `products` VALUES(7761,38,"urenga nguo","pendre un vêtement","_","active");
INSERT INTO `products` VALUES(7762,38,"usuka nyole","tresser les cheveux","_","active");
INSERT INTO `products` VALUES(7763,38,"utoa","enlever","_","active");
INSERT INTO `products` VALUES(7764,38,"utoa kavi","enlever les boucles d'oreille","_","active");
INSERT INTO `products` VALUES(7765,38,"utoa nguo","se déshabiller","_","active");
INSERT INTO `products` VALUES(7766,38,"utoa trotro","enlever la saleté","_","active");
INSERT INTO `products` VALUES(7767,38,"utoa verni","enlever le vernis à ongle","_","active");
INSERT INTO `products` VALUES(7768,38,"utria ina","mettre du henné","_","active");
INSERT INTO `products` VALUES(7769,38,"utria mlala","mettre du rouge à lèvre","_","active");
INSERT INTO `products` VALUES(7770,38,"utria pere","mettre une bague","_","active");
INSERT INTO `products` VALUES(7771,38,"utria trotro","salir","_","active");
INSERT INTO `products` VALUES(7772,38,"utsaha","vouloir","_","active");
INSERT INTO `products` VALUES(7773,38,"uvera","plier","_","active");
INSERT INTO `products` VALUES(7774,38,"uvimisa","mesurer","_","active");
INSERT INTO `products` VALUES(7775,34,"bafu","baffle","_","active");
INSERT INTO `products` VALUES(7776,34,"batri","batterie","_","active");
INSERT INTO `products` VALUES(7777,34,"gabusi","gabousse, luth","_","active");
INSERT INTO `products` VALUES(7778,34,"gitari","guitare","_","active");
INSERT INTO `products` VALUES(7779,34,"kayamba","kayambe, percussion","_","active");
INSERT INTO `products` VALUES(7780,34,"mikro","micro","_","active");
INSERT INTO `products` VALUES(7781,34,"ngoma","tam-tam","_","active");
INSERT INTO `products` VALUES(7782,34,"tari","tambourin","_","active");
INSERT INTO `products` VALUES(7783,34,"biaya","danse avec un bâton (hommes)","_","active");
INSERT INTO `products` VALUES(7784,34,"daira","fête religieuse (hommes)","_","active");
INSERT INTO `products` VALUES(7785,34,"deba","chant religieux rythmé (femmes)","_","active");
INSERT INTO `products` VALUES(7786,34,"maulida shenge","fête à la mosquée (hommes)","_","active");
INSERT INTO `products` VALUES(7787,34,"mbiwi","danse rythmée par des bois frappés (femmes)","_","active");
INSERT INTO `products` VALUES(7788,34,"mgodro","danse traditionnelle","_","active");
INSERT INTO `products` VALUES(7789,34,"mlelezi","danse en cortège pour les nouveaux mariés","_","active");
INSERT INTO `products` VALUES(7790,34,"mulidi","danse avec l'épée (hommes)","_","active");
INSERT INTO `products` VALUES(7791,34,"murenge","lutte mahoraise (hommes)","_","active");
INSERT INTO `products` VALUES(7792,34,"namandzia","danse lors du mariage (femmes)","_","active");
INSERT INTO `products` VALUES(7793,34,"ngoma ya nyombe","tam-tam bœuf","_","active");
INSERT INTO `products` VALUES(7794,34,"shigoma","danse avec un châle","_","active");
INSERT INTO `products` VALUES(7795,34,"twarabu","danse avec la canne (hommes)","_","active");
INSERT INTO `products` VALUES(7796,34,"wadaha","danse avec le mortier et le pilon (femmes)","_","active");
INSERT INTO `products` VALUES(7797,34,"asidungisa fetre","elle balance très bien","_","active");
INSERT INTO `products` VALUES(7798,34,"bwi ! unu dunia","oh la la ! Que de monde","_","active");
INSERT INTO `products` VALUES(7799,34,"himbo iyo ndzuzuri","cette chanson est bonne","_","active");
INSERT INTO `products` VALUES(7800,34,"nisendra harimwa konser","je vais à un concert","_","active");
INSERT INTO `products` VALUES(7801,34,"wahimbizi wanu uzina sawa","ces chanteurs dansent à pas égaux","_","active");
INSERT INTO `products` VALUES(7802,34,"wapindri sawa","ils sont habillés pareil","_","active");
INSERT INTO `products` VALUES(7803,34,"wasibadza","elles font des gestes maniérés","_","active");
INSERT INTO `products` VALUES(7804,34,"waye ujua uzina","elle sait danser","_","active");
INSERT INTO `products` VALUES(7805,34,"wewe ujua uhimba","tu sais chanter","_","active");
INSERT INTO `products` VALUES(7806,34,"ubadza","danser avec de simples mouvements","_","active");
INSERT INTO `products` VALUES(7807,34,"ubiha masama","applaudir","_","active");
INSERT INTO `products` VALUES(7808,34,"ubiha ngoma","frapper le tambour","_","active");
INSERT INTO `products` VALUES(7809,34,"udjidungisa","se bouger en dansant","_","active");
INSERT INTO `products` VALUES(7810,34,"udjirengeledza","se préparer","_","active");
INSERT INTO `products` VALUES(7811,34,"uendra ngomani","aller à la fête","_","active");
INSERT INTO `products` VALUES(7812,34,"ufundriha uzina","apprendre à danser","_","active");
INSERT INTO `products` VALUES(7813,34,"uhedza deba","chanter en solo","_","active");
INSERT INTO `products` VALUES(7814,34,"uhimba","chanter","_","active");
INSERT INTO `products` VALUES(7815,34,"uketsi","s'asseoir","_","active");
INSERT INTO `products` VALUES(7816,34,"ulatsa keme","crier","_","active");
INSERT INTO `products` VALUES(7817,34,"ungadza","jouer","_","active");
INSERT INTO `products` VALUES(7818,34,"ununua zombo","acheter les instruments","_","active");
INSERT INTO `products` VALUES(7819,34,"upindra sare","porter le même modèle","_","active");
INSERT INTO `products` VALUES(7820,34,"urema tari","jouer du tambourin","_","active");
INSERT INTO `products` VALUES(7821,34,"utsahua mvelesheleyo","choisir le refrain","_","active");
INSERT INTO `products` VALUES(7822,34,"utseha","rire","_","active");
INSERT INTO `products` VALUES(7823,34,"utsema","chuchoter","_","active");
INSERT INTO `products` VALUES(7824,34,"utrunga","inventer, composer","_","active");
INSERT INTO `products` VALUES(7825,34,"utwali","réviser","_","active");
INSERT INTO `products` VALUES(7826,34,"uvumua","se reposer","_","active");
INSERT INTO `products` VALUES(7827,34,"uzina","danser","_","active");
INSERT INTO `products` VALUES(7828,34,"uzina shigoma","danser le shigoma","_","active");
INSERT INTO `products` VALUES(7829,34,"uzina wadaha","danser le wadaha","_","active");
INSERT INTO `products` VALUES(7830,34,"uzunguha fikira","chercher des idées","_","active");
INSERT INTO `products` VALUES(7831,30,"baanzi","voilier","_","active");
INSERT INTO `products` VALUES(7832,30,"dziwaro","marlin","_","active");
INSERT INTO `products` VALUES(7833,30,"fumba-ndruju","dauphin","_","active");
INSERT INTO `products` VALUES(7834,30,"gubera","cœlacanthe","_","active");
INSERT INTO `products` VALUES(7835,30,"hanale","maquereau","_","active");
INSERT INTO `products` VALUES(7836,30,"itrili","poisson rouge","_","active");
INSERT INTO `products` VALUES(7837,30,"kawa","carangue","_","active");
INSERT INTO `products` VALUES(7838,30,"kuba","raie","_","active");
INSERT INTO `products` VALUES(7839,30,"mbasi (mimbasi)","thon","_","active");
INSERT INTO `products` VALUES(7840,30,"mhudana","baracouda","_","active");
INSERT INTO `products` VALUES(7841,30,"mhudraji","poisson-chat","_","active");
INSERT INTO `products` VALUES(7842,30,"mtontso","espadon","_","active");
INSERT INTO `products` VALUES(7843,30,"muhunga","murène","_","active");
INSERT INTO `products` VALUES(7844,30,"muzusi","mérou","_","active");
INSERT INTO `products` VALUES(7845,30,"ndiashe","rouget","_","active");
INSERT INTO `products` VALUES(7846,30,"nungu","poisson lune","_","active");
INSERT INTO `products` VALUES(7847,30,"papa / pãpa / mpãpa","requin","_","active");
INSERT INTO `products` VALUES(7848,30,"papa bingusi","requin marteau","_","active");
INSERT INTO `products` VALUES(7849,30,"pandje","daurade","_","active");
INSERT INTO `products` VALUES(7850,30,"pono","poisson perroquet","_","active");
INSERT INTO `products` VALUES(7851,30,"pwere","bonite","_","active");
INSERT INTO `products` VALUES(7852,30,"sale","tanche","_","active");
INSERT INTO `products` VALUES(7853,30,"sardini","sardine","_","active");
INSERT INTO `products` VALUES(7854,30,"tsehele","cabot","_","active");
INSERT INTO `products` VALUES(7855,30,"dradraka","crabe","_","active");
INSERT INTO `products` VALUES(7856,30,"gagasi (ma-)","oursin","_","active");
INSERT INTO `products` VALUES(7857,30,"gulahu","casque rouge (coquillage)","_","active");
INSERT INTO `products` VALUES(7858,30,"jani (ma-)","algue","_","active");
INSERT INTO `products` VALUES(7859,30,"kamba","crevette","_","active");
INSERT INTO `products` VALUES(7860,30,"kamba diva","langouste","_","active");
INSERT INTO `products` VALUES(7861,30,"kombe (mahombe)","coquillage","_","active");
INSERT INTO `products` VALUES(7862,30,"ndruju","baleine","_","active");
INSERT INTO `products` VALUES(7863,30,"ndruju bile","baleine bleue","_","active");
INSERT INTO `products` VALUES(7864,30,"nyamba / kasa","tortue","_","active");
INSERT INTO `products` VALUES(7865,30,"nyora ya baharini","étoile de mer","_","active");
INSERT INTO `products` VALUES(7866,30,"pwedza langisi","calmar","_","active");
INSERT INTO `products` VALUES(7867,30,"trondro","bigorneau","_","active");
INSERT INTO `products` VALUES(7868,30,"duja (maluja)","vague","_","active");
INSERT INTO `products` VALUES(7869,30,"maji ya shingo","eau de mer","_","active");
INSERT INTO `products` VALUES(7870,30,"muhõko","mangrove","_","active");
INSERT INTO `products` VALUES(7871,30,"mutsanga","sable","_","active");
INSERT INTO `products` VALUES(7872,30,"mutsangani","plage","_","active");
INSERT INTO `products` VALUES(7873,30,"mwamba","corail","_","active");
INSERT INTO `products` VALUES(7874,30,"mwambani","barrière de corail","_","active");
INSERT INTO `products` VALUES(7875,30,"panga","grotte","_","active");
INSERT INTO `products` VALUES(7876,30,"shisiwa","île","_","active");
INSERT INTO `products` VALUES(7877,30,"shisiwa ya komba","îlot Mbouzi","_","active");
INSERT INTO `products` VALUES(7878,30,"shisiwa ya mtsanga njeu","îlot de Sable Blanc","_","active");
INSERT INTO `products` VALUES(7879,30,"maji yawendre","marée","_","active");
INSERT INTO `products` VALUES(7880,30,"maji yavihedza","marée très haute","_","active");
INSERT INTO `products` VALUES(7881,30,"maji yajaya","marée haute","_","active");
INSERT INTO `products` VALUES(7882,30,"maji yalala","marée étale","_","active");
INSERT INTO `products` VALUES(7883,30,"maji yashuko","marée descendante","_","active");
INSERT INTO `products` VALUES(7884,30,"maji yahaya","marée basse","_","active");
INSERT INTO `products` VALUES(7885,30,"maji yatruliya","mer calme","_","active");
INSERT INTO `products` VALUES(7886,30,"bati","flotteur","_","active");
INSERT INTO `products` VALUES(7887,30,"djahazi","boutre","_","active");
INSERT INTO `products` VALUES(7888,30,"kasi","rame","_","active");
INSERT INTO `products` VALUES(7889,30,"laka","pirogue","_","active");
INSERT INTO `products` VALUES(7890,30,"markabu","bateau","_","active");
INSERT INTO `products` VALUES(7891,30,"misi","pêche à la ligne","_","active");
INSERT INTO `products` VALUES(7892,30,"ulo","hameçon","_","active");
INSERT INTO `products` VALUES(7893,30,"unyavu","pêche au filet","_","active");
INSERT INTO `products` VALUES(7894,30,"urara","pêche à la traîne","_","active");
INSERT INTO `products` VALUES(7895,30,"utratrishia","pêche au piquet","_","active");
INSERT INTO `products` VALUES(7896,30,"utria uvura","pêche au poison","_","active");
INSERT INTO `products` VALUES(7897,30,"uvura","pêche à marée basse","_","active");
INSERT INTO `products` VALUES(7898,30,"avingwa na maji","il est emporté par le courant","_","active");
INSERT INTO `products` VALUES(7899,30,"bahari ilala","la mer est calme","_","active");
INSERT INTO `products` VALUES(7900,30,"daruba","un cyclone","_","active");
INSERT INTO `products` VALUES(7901,30,"fi zisilisa","la pêche est bonne","_","active");
INSERT INTO `products` VALUES(7902,30,"ini kashkazi","c'est la saison chaude","_","active");
INSERT INTO `products` VALUES(7903,30,"juwa la kali","le soleil est fort","_","active");
INSERT INTO `products` VALUES(7904,30,"lini kusi","c'est la saison sèche","_","active");
INSERT INTO `products` VALUES(7905,30,"maji yasivira","il y a du courant","_","active");
INSERT INTO `products` VALUES(7906,30,"pevo isivuma","le vent souffle","_","active");
INSERT INTO `products` VALUES(7907,30,"vwa maluja","il y a des vagues","_","active");
INSERT INTO `products` VALUES(7908,30,"vwa pevo","il y a du vent","_","active");
INSERT INTO `products` VALUES(7909,30,"ufanya fi","préparer du poisson","_","active");
INSERT INTO `products` VALUES(7910,30,"uheleya","nager","_","active");
INSERT INTO `products` VALUES(7911,30,"ukasi","ramer","_","active");
INSERT INTO `products` VALUES(7912,30,"ulowa","pêcher","_","active");
INSERT INTO `products` VALUES(7913,30,"unwa maji","se noyer","_","active");
INSERT INTO `products` VALUES(7914,30,"upashia","embarquer","_","active");
INSERT INTO `products` VALUES(7915,30,"usika fi","attraper du poisson","_","active");
INSERT INTO `products` VALUES(7916,30,"utoa mamba","enlever les écailles","_","active");
INSERT INTO `products` VALUES(7917,30,"utoa yamarimbo","vider le poisson","_","active");